// Code generated by mockery v2.53.3. DO NOT EDIT.

package reports

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// BranchBreakdown provides a mock function with given fields: ctx, orgID, branchID, from, to
func (_m *MockRepository) BranchBreakdown(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time) ([]BranchBreakdown, error) {
	ret := _m.Called(ctx, orgID, branchID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for BranchBreakdown")
	}

	var r0 []BranchBreakdown
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time) ([]BranchBreakdown, error)); ok {
		return rf(ctx, orgID, branchID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time) []BranchBreakdown); ok {
		r0 = rf(ctx, orgID, branchID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BranchBreakdown)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint, time.Time, time.Time) error); ok {
		r1 = rf(ctx, orgID, branchID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_BranchBreakdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BranchBreakdown'
type MockRepository_BranchBreakdown_Call struct {
	*mock.Call
}

// BranchBreakdown is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
//   - from time.Time
//   - to time.Time
func (_e *MockRepository_Expecter) BranchBreakdown(ctx interface{}, orgID interface{}, branchID interface{}, from interface{}, to interface{}) *MockRepository_BranchBreakdown_Call {
	return &MockRepository_BranchBreakdown_Call{Call: _e.mock.On("BranchBreakdown", ctx, orgID, branchID, from, to)}
}

func (_c *MockRepository_BranchBreakdown_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time)) *MockRepository_BranchBreakdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *MockRepository_BranchBreakdown_Call) Return(_a0 []BranchBreakdown, _a1 error) *MockRepository_BranchBreakdown_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_BranchBreakdown_Call) RunAndReturn(run func(context.Context, uint, *uint, time.Time, time.Time) ([]BranchBreakdown, error)) *MockRepository_BranchBreakdown_Call {
	_c.Call.Return(run)
	return _c
}

// COGS provides a mock function with given fields: ctx, orgID, branchID, from, to
func (_m *MockRepository) COGS(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time) (decimal.Decimal, error) {
	ret := _m.Called(ctx, orgID, branchID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for COGS")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time) (decimal.Decimal, error)); ok {
		return rf(ctx, orgID, branchID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time) decimal.Decimal); ok {
		r0 = rf(ctx, orgID, branchID, from, to)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint, time.Time, time.Time) error); ok {
		r1 = rf(ctx, orgID, branchID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_COGS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'COGS'
type MockRepository_COGS_Call struct {
	*mock.Call
}

// COGS is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
//   - from time.Time
//   - to time.Time
func (_e *MockRepository_Expecter) COGS(ctx interface{}, orgID interface{}, branchID interface{}, from interface{}, to interface{}) *MockRepository_COGS_Call {
	return &MockRepository_COGS_Call{Call: _e.mock.On("COGS", ctx, orgID, branchID, from, to)}
}

func (_c *MockRepository_COGS_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time)) *MockRepository_COGS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *MockRepository_COGS_Call) Return(_a0 decimal.Decimal, _a1 error) *MockRepository_COGS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_COGS_Call) RunAndReturn(run func(context.Context, uint, *uint, time.Time, time.Time) (decimal.Decimal, error)) *MockRepository_COGS_Call {
	_c.Call.Return(run)
	return _c
}

// CategoryBreakdown provides a mock function with given fields: ctx, orgID, branchID, from, to
func (_m *MockRepository) CategoryBreakdown(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time) ([]CategoryBreakdown, error) {
	ret := _m.Called(ctx, orgID, branchID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for CategoryBreakdown")
	}

	var r0 []CategoryBreakdown
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time) ([]CategoryBreakdown, error)); ok {
		return rf(ctx, orgID, branchID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time) []CategoryBreakdown); ok {
		r0 = rf(ctx, orgID, branchID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]CategoryBreakdown)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint, time.Time, time.Time) error); ok {
		r1 = rf(ctx, orgID, branchID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CategoryBreakdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CategoryBreakdown'
type MockRepository_CategoryBreakdown_Call struct {
	*mock.Call
}

// CategoryBreakdown is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
//   - from time.Time
//   - to time.Time
func (_e *MockRepository_Expecter) CategoryBreakdown(ctx interface{}, orgID interface{}, branchID interface{}, from interface{}, to interface{}) *MockRepository_CategoryBreakdown_Call {
	return &MockRepository_CategoryBreakdown_Call{Call: _e.mock.On("CategoryBreakdown", ctx, orgID, branchID, from, to)}
}

func (_c *MockRepository_CategoryBreakdown_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time)) *MockRepository_CategoryBreakdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *MockRepository_CategoryBreakdown_Call) Return(_a0 []CategoryBreakdown, _a1 error) *MockRepository_CategoryBreakdown_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CategoryBreakdown_Call) RunAndReturn(run func(context.Context, uint, *uint, time.Time, time.Time) ([]CategoryBreakdown, error)) *MockRepository_CategoryBreakdown_Call {
	_c.Call.Return(run)
	return _c
}

// Expenses provides a mock function with given fields: ctx, branchIDs, from, to
func (_m *MockRepository) Expenses(ctx context.Context, branchIDs []uint, from time.Time, to time.Time) (decimal.Decimal, error) {
	ret := _m.Called(ctx, branchIDs, from, to)

	if len(ret) == 0 {
		panic("no return value specified for Expenses")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint, time.Time, time.Time) (decimal.Decimal, error)); ok {
		return rf(ctx, branchIDs, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint, time.Time, time.Time) decimal.Decimal); ok {
		r0 = rf(ctx, branchIDs, from, to)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint, time.Time, time.Time) error); ok {
		r1 = rf(ctx, branchIDs, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Expenses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Expenses'
type MockRepository_Expenses_Call struct {
	*mock.Call
}

// Expenses is a helper method to define mock.On call
//   - ctx context.Context
//   - branchIDs []uint
//   - from time.Time
//   - to time.Time
func (_e *MockRepository_Expecter) Expenses(ctx interface{}, branchIDs interface{}, from interface{}, to interface{}) *MockRepository_Expenses_Call {
	return &MockRepository_Expenses_Call{Call: _e.mock.On("Expenses", ctx, branchIDs, from, to)}
}

func (_c *MockRepository_Expenses_Call) Run(run func(ctx context.Context, branchIDs []uint, from time.Time, to time.Time)) *MockRepository_Expenses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepository_Expenses_Call) Return(_a0 decimal.Decimal, _a1 error) *MockRepository_Expenses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Expenses_Call) RunAndReturn(run func(context.Context, []uint, time.Time, time.Time) (decimal.Decimal, error)) *MockRepository_Expenses_Call {
	_c.Call.Return(run)
	return _c
}

// HourlyTrend provides a mock function with given fields: ctx, orgID, branchID, dayStart, dayEnd, timezone
func (_m *MockRepository) HourlyTrend(ctx context.Context, orgID uint, branchID *uint, dayStart time.Time, dayEnd time.Time, timezone string) ([]TrendBucket, error) {
	ret := _m.Called(ctx, orgID, branchID, dayStart, dayEnd, timezone)

	if len(ret) == 0 {
		panic("no return value specified for HourlyTrend")
	}

	var r0 []TrendBucket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time, string) ([]TrendBucket, error)); ok {
		return rf(ctx, orgID, branchID, dayStart, dayEnd, timezone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time, string) []TrendBucket); ok {
		r0 = rf(ctx, orgID, branchID, dayStart, dayEnd, timezone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TrendBucket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint, time.Time, time.Time, string) error); ok {
		r1 = rf(ctx, orgID, branchID, dayStart, dayEnd, timezone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_HourlyTrend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HourlyTrend'
type MockRepository_HourlyTrend_Call struct {
	*mock.Call
}

// HourlyTrend is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
//   - dayStart time.Time
//   - dayEnd time.Time
//   - timezone string
func (_e *MockRepository_Expecter) HourlyTrend(ctx interface{}, orgID interface{}, branchID interface{}, dayStart interface{}, dayEnd interface{}, timezone interface{}) *MockRepository_HourlyTrend_Call {
	return &MockRepository_HourlyTrend_Call{Call: _e.mock.On("HourlyTrend", ctx, orgID, branchID, dayStart, dayEnd, timezone)}
}

func (_c *MockRepository_HourlyTrend_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint, dayStart time.Time, dayEnd time.Time, timezone string)) *MockRepository_HourlyTrend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint), args[3].(time.Time), args[4].(time.Time), args[5].(string))
	})
	return _c
}

func (_c *MockRepository_HourlyTrend_Call) Return(_a0 []TrendBucket, _a1 error) *MockRepository_HourlyTrend_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_HourlyTrend_Call) RunAndReturn(run func(context.Context, uint, *uint, time.Time, time.Time, string) ([]TrendBucket, error)) *MockRepository_HourlyTrend_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransactions provides a mock function with given fields: ctx, orgID, branchID, from, to, page, pageSize
func (_m *MockRepository) ListTransactions(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time, page int, pageSize int) ([]TransactionSummary, int64, error) {
	ret := _m.Called(ctx, orgID, branchID, from, to, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListTransactions")
	}

	var r0 []TransactionSummary
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time, int, int) ([]TransactionSummary, int64, error)); ok {
		return rf(ctx, orgID, branchID, from, to, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time, int, int) []TransactionSummary); ok {
		r0 = rf(ctx, orgID, branchID, from, to, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TransactionSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint, time.Time, time.Time, int, int) int64); ok {
		r1 = rf(ctx, orgID, branchID, from, to, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, *uint, time.Time, time.Time, int, int) error); ok {
		r2 = rf(ctx, orgID, branchID, from, to, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_ListTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransactions'
type MockRepository_ListTransactions_Call struct {
	*mock.Call
}

// ListTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
//   - from time.Time
//   - to time.Time
//   - page int
//   - pageSize int
func (_e *MockRepository_Expecter) ListTransactions(ctx interface{}, orgID interface{}, branchID interface{}, from interface{}, to interface{}, page interface{}, pageSize interface{}) *MockRepository_ListTransactions_Call {
	return &MockRepository_ListTransactions_Call{Call: _e.mock.On("ListTransactions", ctx, orgID, branchID, from, to, page, pageSize)}
}

func (_c *MockRepository_ListTransactions_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time, page int, pageSize int)) *MockRepository_ListTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint), args[3].(time.Time), args[4].(time.Time), args[5].(int), args[6].(int))
	})
	return _c
}

func (_c *MockRepository_ListTransactions_Call) Return(_a0 []TransactionSummary, _a1 int64, _a2 error) *MockRepository_ListTransactions_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_ListTransactions_Call) RunAndReturn(run func(context.Context, uint, *uint, time.Time, time.Time, int, int) ([]TransactionSummary, int64, error)) *MockRepository_ListTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// PaymentMethodBreakdown provides a mock function with given fields: ctx, orgID, branchID, from, to
func (_m *MockRepository) PaymentMethodBreakdown(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time) ([]PaymentMethodBreakdown, error) {
	ret := _m.Called(ctx, orgID, branchID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for PaymentMethodBreakdown")
	}

	var r0 []PaymentMethodBreakdown
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time) ([]PaymentMethodBreakdown, error)); ok {
		return rf(ctx, orgID, branchID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time) []PaymentMethodBreakdown); ok {
		r0 = rf(ctx, orgID, branchID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PaymentMethodBreakdown)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint, time.Time, time.Time) error); ok {
		r1 = rf(ctx, orgID, branchID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_PaymentMethodBreakdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PaymentMethodBreakdown'
type MockRepository_PaymentMethodBreakdown_Call struct {
	*mock.Call
}

// PaymentMethodBreakdown is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
//   - from time.Time
//   - to time.Time
func (_e *MockRepository_Expecter) PaymentMethodBreakdown(ctx interface{}, orgID interface{}, branchID interface{}, from interface{}, to interface{}) *MockRepository_PaymentMethodBreakdown_Call {
	return &MockRepository_PaymentMethodBreakdown_Call{Call: _e.mock.On("PaymentMethodBreakdown", ctx, orgID, branchID, from, to)}
}

func (_c *MockRepository_PaymentMethodBreakdown_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time)) *MockRepository_PaymentMethodBreakdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *MockRepository_PaymentMethodBreakdown_Call) Return(_a0 []PaymentMethodBreakdown, _a1 error) *MockRepository_PaymentMethodBreakdown_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_PaymentMethodBreakdown_Call) RunAndReturn(run func(context.Context, uint, *uint, time.Time, time.Time) ([]PaymentMethodBreakdown, error)) *MockRepository_PaymentMethodBreakdown_Call {
	_c.Call.Return(run)
	return _c
}

// PaymentMethodsBySale provides a mock function with given fields: ctx, saleIDs
func (_m *MockRepository) PaymentMethodsBySale(ctx context.Context, saleIDs []uuid.UUID) (map[uuid.UUID][]string, error) {
	ret := _m.Called(ctx, saleIDs)

	if len(ret) == 0 {
		panic("no return value specified for PaymentMethodsBySale")
	}

	var r0 map[uuid.UUID][]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID][]string, error)); ok {
		return rf(ctx, saleIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID][]string); ok {
		r0 = rf(ctx, saleIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, saleIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_PaymentMethodsBySale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PaymentMethodsBySale'
type MockRepository_PaymentMethodsBySale_Call struct {
	*mock.Call
}

// PaymentMethodsBySale is a helper method to define mock.On call
//   - ctx context.Context
//   - saleIDs []uuid.UUID
func (_e *MockRepository_Expecter) PaymentMethodsBySale(ctx interface{}, saleIDs interface{}) *MockRepository_PaymentMethodsBySale_Call {
	return &MockRepository_PaymentMethodsBySale_Call{Call: _e.mock.On("PaymentMethodsBySale", ctx, saleIDs)}
}

func (_c *MockRepository_PaymentMethodsBySale_Call) Run(run func(ctx context.Context, saleIDs []uuid.UUID)) *MockRepository_PaymentMethodsBySale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_PaymentMethodsBySale_Call) Return(_a0 map[uuid.UUID][]string, _a1 error) *MockRepository_PaymentMethodsBySale_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_PaymentMethodsBySale_Call) RunAndReturn(run func(context.Context, []uuid.UUID) (map[uuid.UUID][]string, error)) *MockRepository_PaymentMethodsBySale_Call {
	_c.Call.Return(run)
	return _c
}

// ProductCounts provides a mock function with given fields: ctx, orgID, branchID
func (_m *MockRepository) ProductCounts(ctx context.Context, orgID uint, branchID *uint) (StockOverview, error) {
	ret := _m.Called(ctx, orgID, branchID)

	if len(ret) == 0 {
		panic("no return value specified for ProductCounts")
	}

	var r0 StockOverview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint) (StockOverview, error)); ok {
		return rf(ctx, orgID, branchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint) StockOverview); ok {
		r0 = rf(ctx, orgID, branchID)
	} else {
		r0 = ret.Get(0).(StockOverview)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint) error); ok {
		r1 = rf(ctx, orgID, branchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ProductCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProductCounts'
type MockRepository_ProductCounts_Call struct {
	*mock.Call
}

// ProductCounts is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
func (_e *MockRepository_Expecter) ProductCounts(ctx interface{}, orgID interface{}, branchID interface{}) *MockRepository_ProductCounts_Call {
	return &MockRepository_ProductCounts_Call{Call: _e.mock.On("ProductCounts", ctx, orgID, branchID)}
}

func (_c *MockRepository_ProductCounts_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint)) *MockRepository_ProductCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint))
	})
	return _c
}

func (_c *MockRepository_ProductCounts_Call) Return(_a0 StockOverview, _a1 error) *MockRepository_ProductCounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ProductCounts_Call) RunAndReturn(run func(context.Context, uint, *uint) (StockOverview, error)) *MockRepository_ProductCounts_Call {
	_c.Call.Return(run)
	return _c
}

// ProductSales provides a mock function with given fields: ctx, orgID, branchID, from, to, categoryID, limit
func (_m *MockRepository) ProductSales(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time, categoryID *uint, limit *int) ([]ProductRevenue, error) {
	ret := _m.Called(ctx, orgID, branchID, from, to, categoryID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ProductSales")
	}

	var r0 []ProductRevenue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time, *uint, *int) ([]ProductRevenue, error)); ok {
		return rf(ctx, orgID, branchID, from, to, categoryID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time, *uint, *int) []ProductRevenue); ok {
		r0 = rf(ctx, orgID, branchID, from, to, categoryID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ProductRevenue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint, time.Time, time.Time, *uint, *int) error); ok {
		r1 = rf(ctx, orgID, branchID, from, to, categoryID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ProductSales_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProductSales'
type MockRepository_ProductSales_Call struct {
	*mock.Call
}

// ProductSales is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
//   - from time.Time
//   - to time.Time
//   - categoryID *uint
//   - limit *int
func (_e *MockRepository_Expecter) ProductSales(ctx interface{}, orgID interface{}, branchID interface{}, from interface{}, to interface{}, categoryID interface{}, limit interface{}) *MockRepository_ProductSales_Call {
	return &MockRepository_ProductSales_Call{Call: _e.mock.On("ProductSales", ctx, orgID, branchID, from, to, categoryID, limit)}
}

func (_c *MockRepository_ProductSales_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time, categoryID *uint, limit *int)) *MockRepository_ProductSales_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint), args[3].(time.Time), args[4].(time.Time), args[5].(*uint), args[6].(*int))
	})
	return _c
}

func (_c *MockRepository_ProductSales_Call) Return(_a0 []ProductRevenue, _a1 error) *MockRepository_ProductSales_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ProductSales_Call) RunAndReturn(run func(context.Context, uint, *uint, time.Time, time.Time, *uint, *int) ([]ProductRevenue, error)) *MockRepository_ProductSales_Call {
	_c.Call.Return(run)
	return _c
}

// ReturnsTotal provides a mock function with given fields: ctx, orgID, branchID, from, to
func (_m *MockRepository) ReturnsTotal(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time) (decimal.Decimal, error) {
	ret := _m.Called(ctx, orgID, branchID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ReturnsTotal")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time) (decimal.Decimal, error)); ok {
		return rf(ctx, orgID, branchID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time) decimal.Decimal); ok {
		r0 = rf(ctx, orgID, branchID, from, to)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint, time.Time, time.Time) error); ok {
		r1 = rf(ctx, orgID, branchID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ReturnsTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReturnsTotal'
type MockRepository_ReturnsTotal_Call struct {
	*mock.Call
}

// ReturnsTotal is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
//   - from time.Time
//   - to time.Time
func (_e *MockRepository_Expecter) ReturnsTotal(ctx interface{}, orgID interface{}, branchID interface{}, from interface{}, to interface{}) *MockRepository_ReturnsTotal_Call {
	return &MockRepository_ReturnsTotal_Call{Call: _e.mock.On("ReturnsTotal", ctx, orgID, branchID, from, to)}
}

func (_c *MockRepository_ReturnsTotal_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time)) *MockRepository_ReturnsTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *MockRepository_ReturnsTotal_Call) Return(_a0 decimal.Decimal, _a1 error) *MockRepository_ReturnsTotal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ReturnsTotal_Call) RunAndReturn(run func(context.Context, uint, *uint, time.Time, time.Time) (decimal.Decimal, error)) *MockRepository_ReturnsTotal_Call {
	_c.Call.Return(run)
	return _c
}

// SalesAggregate provides a mock function with given fields: ctx, orgID, branchID, from, to
func (_m *MockRepository) SalesAggregate(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time) (SalesAggregate, error) {
	ret := _m.Called(ctx, orgID, branchID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SalesAggregate")
	}

	var r0 SalesAggregate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time) (SalesAggregate, error)); ok {
		return rf(ctx, orgID, branchID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time) SalesAggregate); ok {
		r0 = rf(ctx, orgID, branchID, from, to)
	} else {
		r0 = ret.Get(0).(SalesAggregate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint, time.Time, time.Time) error); ok {
		r1 = rf(ctx, orgID, branchID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_SalesAggregate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SalesAggregate'
type MockRepository_SalesAggregate_Call struct {
	*mock.Call
}

// SalesAggregate is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
//   - from time.Time
//   - to time.Time
func (_e *MockRepository_Expecter) SalesAggregate(ctx interface{}, orgID interface{}, branchID interface{}, from interface{}, to interface{}) *MockRepository_SalesAggregate_Call {
	return &MockRepository_SalesAggregate_Call{Call: _e.mock.On("SalesAggregate", ctx, orgID, branchID, from, to)}
}

func (_c *MockRepository_SalesAggregate_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time)) *MockRepository_SalesAggregate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *MockRepository_SalesAggregate_Call) Return(_a0 SalesAggregate, _a1 error) *MockRepository_SalesAggregate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_SalesAggregate_Call) RunAndReturn(run func(context.Context, uint, *uint, time.Time, time.Time) (SalesAggregate, error)) *MockRepository_SalesAggregate_Call {
	_c.Call.Return(run)
	return _c
}

// Trend provides a mock function with given fields: ctx, orgID, branchID, from, to, granularity, timezone
func (_m *MockRepository) Trend(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time, granularity Granularity, timezone string) ([]TrendBucket, error) {
	ret := _m.Called(ctx, orgID, branchID, from, to, granularity, timezone)

	if len(ret) == 0 {
		panic("no return value specified for Trend")
	}

	var r0 []TrendBucket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time, Granularity, string) ([]TrendBucket, error)); ok {
		return rf(ctx, orgID, branchID, from, to, granularity, timezone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, time.Time, time.Time, Granularity, string) []TrendBucket); ok {
		r0 = rf(ctx, orgID, branchID, from, to, granularity, timezone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TrendBucket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint, time.Time, time.Time, Granularity, string) error); ok {
		r1 = rf(ctx, orgID, branchID, from, to, granularity, timezone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Trend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trend'
type MockRepository_Trend_Call struct {
	*mock.Call
}

// Trend is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
//   - from time.Time
//   - to time.Time
//   - granularity Granularity
//   - timezone string
func (_e *MockRepository_Expecter) Trend(ctx interface{}, orgID interface{}, branchID interface{}, from interface{}, to interface{}, granularity interface{}, timezone interface{}) *MockRepository_Trend_Call {
	return &MockRepository_Trend_Call{Call: _e.mock.On("Trend", ctx, orgID, branchID, from, to, granularity, timezone)}
}

func (_c *MockRepository_Trend_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint, from time.Time, to time.Time, granularity Granularity, timezone string)) *MockRepository_Trend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint), args[3].(time.Time), args[4].(time.Time), args[5].(Granularity), args[6].(string))
	})
	return _c
}

func (_c *MockRepository_Trend_Call) Return(_a0 []TrendBucket, _a1 error) *MockRepository_Trend_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Trend_Call) RunAndReturn(run func(context.Context, uint, *uint, time.Time, time.Time, Granularity, string) ([]TrendBucket, error)) *MockRepository_Trend_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
