with-expecter: true
packages:
  shagan_pos/internal/identity:
    config:
      dir: "internal/identity"
      outpkg: identity
      inpackage: true
    interfaces:
      Repository:
        config:
          filename: "mock_identity_repository_test.go"
  shagan_pos/internal/catalog:
    config:
      dir: "internal/catalog"
      outpkg: catalog
      inpackage: true
    interfaces:
      Repository:
        config:
          filename: "mock_catalog_repository_test.go"
  shagan_pos/internal/customer:
    config:
      dir: "internal/customer"
      outpkg: customer
      inpackage: true
    interfaces:
      Repository:
        config:
          filename: "mock_customer_repository_test.go"
