// Code generated by mockery v2.53.3. DO NOT EDIT.

package platform

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreatePaymentQRCode provides a mock function with given fields: db, qr
func (_m *MockRepository) CreatePaymentQRCode(db *gorm.DB, qr *PaymentQRCode) error {
	ret := _m.Called(db, qr)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentQRCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *PaymentQRCode) error); ok {
		r0 = rf(db, qr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreatePaymentQRCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePaymentQRCode'
type MockRepository_CreatePaymentQRCode_Call struct {
	*mock.Call
}

// CreatePaymentQRCode is a helper method to define mock.On call
//   - db *gorm.DB
//   - qr *PaymentQRCode
func (_e *MockRepository_Expecter) CreatePaymentQRCode(db interface{}, qr interface{}) *MockRepository_CreatePaymentQRCode_Call {
	return &MockRepository_CreatePaymentQRCode_Call{Call: _e.mock.On("CreatePaymentQRCode", db, qr)}
}

func (_c *MockRepository_CreatePaymentQRCode_Call) Run(run func(db *gorm.DB, qr *PaymentQRCode)) *MockRepository_CreatePaymentQRCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*PaymentQRCode))
	})
	return _c
}

func (_c *MockRepository_CreatePaymentQRCode_Call) Return(_a0 error) *MockRepository_CreatePaymentQRCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreatePaymentQRCode_Call) RunAndReturn(run func(*gorm.DB, *PaymentQRCode) error) *MockRepository_CreatePaymentQRCode_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivatePaymentQRCode provides a mock function with given fields: db, id
func (_m *MockRepository) DeactivatePaymentQRCode(db *gorm.DB, id uint) error {
	ret := _m.Called(db, id)

	if len(ret) == 0 {
		panic("no return value specified for DeactivatePaymentQRCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) error); ok {
		r0 = rf(db, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeactivatePaymentQRCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivatePaymentQRCode'
type MockRepository_DeactivatePaymentQRCode_Call struct {
	*mock.Call
}

// DeactivatePaymentQRCode is a helper method to define mock.On call
//   - db *gorm.DB
//   - id uint
func (_e *MockRepository_Expecter) DeactivatePaymentQRCode(db interface{}, id interface{}) *MockRepository_DeactivatePaymentQRCode_Call {
	return &MockRepository_DeactivatePaymentQRCode_Call{Call: _e.mock.On("DeactivatePaymentQRCode", db, id)}
}

func (_c *MockRepository_DeactivatePaymentQRCode_Call) Run(run func(db *gorm.DB, id uint)) *MockRepository_DeactivatePaymentQRCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_DeactivatePaymentQRCode_Call) Return(_a0 error) *MockRepository_DeactivatePaymentQRCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeactivatePaymentQRCode_Call) RunAndReturn(run func(*gorm.DB, uint) error) *MockRepository_DeactivatePaymentQRCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetPaymentQRCode provides a mock function with given fields: ctx, branchID, id
func (_m *MockRepository) GetPaymentQRCode(ctx context.Context, branchID uint, id uint) (*PaymentQRCode, error) {
	ret := _m.Called(ctx, branchID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentQRCode")
	}

	var r0 *PaymentQRCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*PaymentQRCode, error)); ok {
		return rf(ctx, branchID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *PaymentQRCode); ok {
		r0 = rf(ctx, branchID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PaymentQRCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, branchID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetPaymentQRCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPaymentQRCode'
type MockRepository_GetPaymentQRCode_Call struct {
	*mock.Call
}

// GetPaymentQRCode is a helper method to define mock.On call
//   - ctx context.Context
//   - branchID uint
//   - id uint
func (_e *MockRepository_Expecter) GetPaymentQRCode(ctx interface{}, branchID interface{}, id interface{}) *MockRepository_GetPaymentQRCode_Call {
	return &MockRepository_GetPaymentQRCode_Call{Call: _e.mock.On("GetPaymentQRCode", ctx, branchID, id)}
}

func (_c *MockRepository_GetPaymentQRCode_Call) Run(run func(ctx context.Context, branchID uint, id uint)) *MockRepository_GetPaymentQRCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockRepository_GetPaymentQRCode_Call) Return(_a0 *PaymentQRCode, _a1 error) *MockRepository_GetPaymentQRCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetPaymentQRCode_Call) RunAndReturn(run func(context.Context, uint, uint) (*PaymentQRCode, error)) *MockRepository_GetPaymentQRCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetReceiptSettings provides a mock function with given fields: ctx, orgID, branchID
func (_m *MockRepository) GetReceiptSettings(ctx context.Context, orgID uint, branchID *uint) (*ReceiptSetting, error) {
	ret := _m.Called(ctx, orgID, branchID)

	if len(ret) == 0 {
		panic("no return value specified for GetReceiptSettings")
	}

	var r0 *ReceiptSetting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint) (*ReceiptSetting, error)); ok {
		return rf(ctx, orgID, branchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint) *ReceiptSetting); ok {
		r0 = rf(ctx, orgID, branchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ReceiptSetting)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint) error); ok {
		r1 = rf(ctx, orgID, branchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetReceiptSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReceiptSettings'
type MockRepository_GetReceiptSettings_Call struct {
	*mock.Call
}

// GetReceiptSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
func (_e *MockRepository_Expecter) GetReceiptSettings(ctx interface{}, orgID interface{}, branchID interface{}) *MockRepository_GetReceiptSettings_Call {
	return &MockRepository_GetReceiptSettings_Call{Call: _e.mock.On("GetReceiptSettings", ctx, orgID, branchID)}
}

func (_c *MockRepository_GetReceiptSettings_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint)) *MockRepository_GetReceiptSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint))
	})
	return _c
}

func (_c *MockRepository_GetReceiptSettings_Call) Return(_a0 *ReceiptSetting, _a1 error) *MockRepository_GetReceiptSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetReceiptSettings_Call) RunAndReturn(run func(context.Context, uint, *uint) (*ReceiptSetting, error)) *MockRepository_GetReceiptSettings_Call {
	_c.Call.Return(run)
	return _c
}

// ListActivePaymentQRCodes provides a mock function with given fields: ctx, branchID
func (_m *MockRepository) ListActivePaymentQRCodes(ctx context.Context, branchID uint) ([]PaymentQRCode, error) {
	ret := _m.Called(ctx, branchID)

	if len(ret) == 0 {
		panic("no return value specified for ListActivePaymentQRCodes")
	}

	var r0 []PaymentQRCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]PaymentQRCode, error)); ok {
		return rf(ctx, branchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []PaymentQRCode); ok {
		r0 = rf(ctx, branchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PaymentQRCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, branchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListActivePaymentQRCodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActivePaymentQRCodes'
type MockRepository_ListActivePaymentQRCodes_Call struct {
	*mock.Call
}

// ListActivePaymentQRCodes is a helper method to define mock.On call
//   - ctx context.Context
//   - branchID uint
func (_e *MockRepository_Expecter) ListActivePaymentQRCodes(ctx interface{}, branchID interface{}) *MockRepository_ListActivePaymentQRCodes_Call {
	return &MockRepository_ListActivePaymentQRCodes_Call{Call: _e.mock.On("ListActivePaymentQRCodes", ctx, branchID)}
}

func (_c *MockRepository_ListActivePaymentQRCodes_Call) Run(run func(ctx context.Context, branchID uint)) *MockRepository_ListActivePaymentQRCodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_ListActivePaymentQRCodes_Call) Return(_a0 []PaymentQRCode, _a1 error) *MockRepository_ListActivePaymentQRCodes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListActivePaymentQRCodes_Call) RunAndReturn(run func(context.Context, uint) ([]PaymentQRCode, error)) *MockRepository_ListActivePaymentQRCodes_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertReceiptSettings provides a mock function with given fields: ctx, orgID, in
func (_m *MockRepository) UpsertReceiptSettings(ctx context.Context, orgID uint, in UpdateReceiptSettingsRequest) (*ReceiptSetting, error) {
	ret := _m.Called(ctx, orgID, in)

	if len(ret) == 0 {
		panic("no return value specified for UpsertReceiptSettings")
	}

	var r0 *ReceiptSetting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, UpdateReceiptSettingsRequest) (*ReceiptSetting, error)); ok {
		return rf(ctx, orgID, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, UpdateReceiptSettingsRequest) *ReceiptSetting); ok {
		r0 = rf(ctx, orgID, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ReceiptSetting)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, UpdateReceiptSettingsRequest) error); ok {
		r1 = rf(ctx, orgID, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpsertReceiptSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertReceiptSettings'
type MockRepository_UpsertReceiptSettings_Call struct {
	*mock.Call
}

// UpsertReceiptSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - in UpdateReceiptSettingsRequest
func (_e *MockRepository_Expecter) UpsertReceiptSettings(ctx interface{}, orgID interface{}, in interface{}) *MockRepository_UpsertReceiptSettings_Call {
	return &MockRepository_UpsertReceiptSettings_Call{Call: _e.mock.On("UpsertReceiptSettings", ctx, orgID, in)}
}

func (_c *MockRepository_UpsertReceiptSettings_Call) Run(run func(ctx context.Context, orgID uint, in UpdateReceiptSettingsRequest)) *MockRepository_UpsertReceiptSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(UpdateReceiptSettingsRequest))
	})
	return _c
}

func (_c *MockRepository_UpsertReceiptSettings_Call) Return(_a0 *ReceiptSetting, _a1 error) *MockRepository_UpsertReceiptSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpsertReceiptSettings_Call) RunAndReturn(run func(context.Context, uint, UpdateReceiptSettingsRequest) (*ReceiptSetting, error)) *MockRepository_UpsertReceiptSettings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
