// Code generated by mockery v2.53.3. DO NOT EDIT.

package returns

import (
	audit "shagan_pos/internal/audit"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// MockAuditWriter is an autogenerated mock type for the AuditWriter type
type MockAuditWriter struct {
	mock.Mock
}

type MockAuditWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditWriter) EXPECT() *MockAuditWriter_Expecter {
	return &MockAuditWriter_Expecter{mock: &_m.Mock}
}

// CreateAuditLog provides a mock function with given fields: db, entry
func (_m *MockAuditWriter) CreateAuditLog(db *gorm.DB, entry *audit.AuditLog) error {
	ret := _m.Called(db, entry)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuditLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *audit.AuditLog) error); ok {
		r0 = rf(db, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditWriter_CreateAuditLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuditLog'
type MockAuditWriter_CreateAuditLog_Call struct {
	*mock.Call
}

// CreateAuditLog is a helper method to define mock.On call
//   - db *gorm.DB
//   - entry *audit.AuditLog
func (_e *MockAuditWriter_Expecter) CreateAuditLog(db interface{}, entry interface{}) *MockAuditWriter_CreateAuditLog_Call {
	return &MockAuditWriter_CreateAuditLog_Call{Call: _e.mock.On("CreateAuditLog", db, entry)}
}

func (_c *MockAuditWriter_CreateAuditLog_Call) Run(run func(db *gorm.DB, entry *audit.AuditLog)) *MockAuditWriter_CreateAuditLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*audit.AuditLog))
	})
	return _c
}

func (_c *MockAuditWriter_CreateAuditLog_Call) Return(_a0 error) *MockAuditWriter_CreateAuditLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditWriter_CreateAuditLog_Call) RunAndReturn(run func(*gorm.DB, *audit.AuditLog) error) *MockAuditWriter_CreateAuditLog_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditWriter creates a new instance of MockAuditWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditWriter {
	mock := &MockAuditWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
