// Code generated by mockery v2.53.3. DO NOT EDIT.

package datasync

import (
	context "context"
	catalog "shagan_pos/internal/catalog"

	mock "github.com/stretchr/testify/mock"
)

// MockCatalogReader is an autogenerated mock type for the CatalogReader type
type MockCatalogReader struct {
	mock.Mock
}

type MockCatalogReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogReader) EXPECT() *MockCatalogReader_Expecter {
	return &MockCatalogReader_Expecter{mock: &_m.Mock}
}

// ListCategories provides a mock function with given fields: ctx, orgID
func (_m *MockCatalogReader) ListCategories(ctx context.Context, orgID uint) ([]catalog.Category, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []catalog.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]catalog.Category, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []catalog.Category); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]catalog.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogReader_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type MockCatalogReader_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
func (_e *MockCatalogReader_Expecter) ListCategories(ctx interface{}, orgID interface{}) *MockCatalogReader_ListCategories_Call {
	return &MockCatalogReader_ListCategories_Call{Call: _e.mock.On("ListCategories", ctx, orgID)}
}

func (_c *MockCatalogReader_ListCategories_Call) Run(run func(ctx context.Context, orgID uint)) *MockCatalogReader_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockCatalogReader_ListCategories_Call) Return(_a0 []catalog.Category, _a1 error) *MockCatalogReader_ListCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogReader_ListCategories_Call) RunAndReturn(run func(context.Context, uint) ([]catalog.Category, error)) *MockCatalogReader_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ListCombos provides a mock function with given fields: ctx, orgID
func (_m *MockCatalogReader) ListCombos(ctx context.Context, orgID uint) ([]catalog.ComboResult, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListCombos")
	}

	var r0 []catalog.ComboResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]catalog.ComboResult, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []catalog.ComboResult); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]catalog.ComboResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogReader_ListCombos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCombos'
type MockCatalogReader_ListCombos_Call struct {
	*mock.Call
}

// ListCombos is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
func (_e *MockCatalogReader_Expecter) ListCombos(ctx interface{}, orgID interface{}) *MockCatalogReader_ListCombos_Call {
	return &MockCatalogReader_ListCombos_Call{Call: _e.mock.On("ListCombos", ctx, orgID)}
}

func (_c *MockCatalogReader_ListCombos_Call) Run(run func(ctx context.Context, orgID uint)) *MockCatalogReader_ListCombos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockCatalogReader_ListCombos_Call) Return(_a0 []catalog.ComboResult, _a1 error) *MockCatalogReader_ListCombos_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogReader_ListCombos_Call) RunAndReturn(run func(context.Context, uint) ([]catalog.ComboResult, error)) *MockCatalogReader_ListCombos_Call {
	_c.Call.Return(run)
	return _c
}

// ListProducts provides a mock function with given fields: ctx, orgID, branchID
func (_m *MockCatalogReader) ListProducts(ctx context.Context, orgID uint, branchID *uint) ([]catalog.ProductResult, error) {
	ret := _m.Called(ctx, orgID, branchID)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 []catalog.ProductResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint) ([]catalog.ProductResult, error)); ok {
		return rf(ctx, orgID, branchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint) []catalog.ProductResult); ok {
		r0 = rf(ctx, orgID, branchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]catalog.ProductResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint) error); ok {
		r1 = rf(ctx, orgID, branchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogReader_ListProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProducts'
type MockCatalogReader_ListProducts_Call struct {
	*mock.Call
}

// ListProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
func (_e *MockCatalogReader_Expecter) ListProducts(ctx interface{}, orgID interface{}, branchID interface{}) *MockCatalogReader_ListProducts_Call {
	return &MockCatalogReader_ListProducts_Call{Call: _e.mock.On("ListProducts", ctx, orgID, branchID)}
}

func (_c *MockCatalogReader_ListProducts_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint)) *MockCatalogReader_ListProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint))
	})
	return _c
}

func (_c *MockCatalogReader_ListProducts_Call) Return(_a0 []catalog.ProductResult, _a1 error) *MockCatalogReader_ListProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogReader_ListProducts_Call) RunAndReturn(run func(context.Context, uint, *uint) ([]catalog.ProductResult, error)) *MockCatalogReader_ListProducts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCatalogReader creates a new instance of MockCatalogReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogReader {
	mock := &MockCatalogReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
