// Code generated by mockery v2.53.3. DO NOT EDIT.

package datasync

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateSyncConflict provides a mock function with given fields: ctx, c
func (_m *MockRepository) CreateSyncConflict(ctx context.Context, c *SyncConflict) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for CreateSyncConflict")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *SyncConflict) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateSyncConflict_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSyncConflict'
type MockRepository_CreateSyncConflict_Call struct {
	*mock.Call
}

// CreateSyncConflict is a helper method to define mock.On call
//   - ctx context.Context
//   - c *SyncConflict
func (_e *MockRepository_Expecter) CreateSyncConflict(ctx interface{}, c interface{}) *MockRepository_CreateSyncConflict_Call {
	return &MockRepository_CreateSyncConflict_Call{Call: _e.mock.On("CreateSyncConflict", ctx, c)}
}

func (_c *MockRepository_CreateSyncConflict_Call) Run(run func(ctx context.Context, c *SyncConflict)) *MockRepository_CreateSyncConflict_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*SyncConflict))
	})
	return _c
}

func (_c *MockRepository_CreateSyncConflict_Call) Return(_a0 error) *MockRepository_CreateSyncConflict_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateSyncConflict_Call) RunAndReturn(run func(context.Context, *SyncConflict) error) *MockRepository_CreateSyncConflict_Call {
	_c.Call.Return(run)
	return _c
}

// GetSyncConflictWithLock provides a mock function with given fields: db, branchIDs, id
func (_m *MockRepository) GetSyncConflictWithLock(db *gorm.DB, branchIDs []uint, id uint) (*SyncConflict, error) {
	ret := _m.Called(db, branchIDs, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSyncConflictWithLock")
	}

	var r0 *SyncConflict
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, []uint, uint) (*SyncConflict, error)); ok {
		return rf(db, branchIDs, id)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, []uint, uint) *SyncConflict); ok {
		r0 = rf(db, branchIDs, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SyncConflict)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, []uint, uint) error); ok {
		r1 = rf(db, branchIDs, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetSyncConflictWithLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSyncConflictWithLock'
type MockRepository_GetSyncConflictWithLock_Call struct {
	*mock.Call
}

// GetSyncConflictWithLock is a helper method to define mock.On call
//   - db *gorm.DB
//   - branchIDs []uint
//   - id uint
func (_e *MockRepository_Expecter) GetSyncConflictWithLock(db interface{}, branchIDs interface{}, id interface{}) *MockRepository_GetSyncConflictWithLock_Call {
	return &MockRepository_GetSyncConflictWithLock_Call{Call: _e.mock.On("GetSyncConflictWithLock", db, branchIDs, id)}
}

func (_c *MockRepository_GetSyncConflictWithLock_Call) Run(run func(db *gorm.DB, branchIDs []uint, id uint)) *MockRepository_GetSyncConflictWithLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].([]uint), args[2].(uint))
	})
	return _c
}

func (_c *MockRepository_GetSyncConflictWithLock_Call) Return(_a0 *SyncConflict, _a1 error) *MockRepository_GetSyncConflictWithLock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetSyncConflictWithLock_Call) RunAndReturn(run func(*gorm.DB, []uint, uint) (*SyncConflict, error)) *MockRepository_GetSyncConflictWithLock_Call {
	_c.Call.Return(run)
	return _c
}

// LastSyncedAt provides a mock function with given fields: ctx, branchIDs
func (_m *MockRepository) LastSyncedAt(ctx context.Context, branchIDs []uint) (*time.Time, error) {
	ret := _m.Called(ctx, branchIDs)

	if len(ret) == 0 {
		panic("no return value specified for LastSyncedAt")
	}

	var r0 *time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) (*time.Time, error)); ok {
		return rf(ctx, branchIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint) *time.Time); ok {
		r0 = rf(ctx, branchIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = rf(ctx, branchIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_LastSyncedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastSyncedAt'
type MockRepository_LastSyncedAt_Call struct {
	*mock.Call
}

// LastSyncedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - branchIDs []uint
func (_e *MockRepository_Expecter) LastSyncedAt(ctx interface{}, branchIDs interface{}) *MockRepository_LastSyncedAt_Call {
	return &MockRepository_LastSyncedAt_Call{Call: _e.mock.On("LastSyncedAt", ctx, branchIDs)}
}

func (_c *MockRepository_LastSyncedAt_Call) Run(run func(ctx context.Context, branchIDs []uint)) *MockRepository_LastSyncedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockRepository_LastSyncedAt_Call) Return(_a0 *time.Time, _a1 error) *MockRepository_LastSyncedAt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_LastSyncedAt_Call) RunAndReturn(run func(context.Context, []uint) (*time.Time, error)) *MockRepository_LastSyncedAt_Call {
	_c.Call.Return(run)
	return _c
}

// ListSyncConflicts provides a mock function with given fields: ctx, branchIDs
func (_m *MockRepository) ListSyncConflicts(ctx context.Context, branchIDs []uint) ([]SyncConflict, error) {
	ret := _m.Called(ctx, branchIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListSyncConflicts")
	}

	var r0 []SyncConflict
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) ([]SyncConflict, error)); ok {
		return rf(ctx, branchIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint) []SyncConflict); ok {
		r0 = rf(ctx, branchIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SyncConflict)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = rf(ctx, branchIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListSyncConflicts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSyncConflicts'
type MockRepository_ListSyncConflicts_Call struct {
	*mock.Call
}

// ListSyncConflicts is a helper method to define mock.On call
//   - ctx context.Context
//   - branchIDs []uint
func (_e *MockRepository_Expecter) ListSyncConflicts(ctx interface{}, branchIDs interface{}) *MockRepository_ListSyncConflicts_Call {
	return &MockRepository_ListSyncConflicts_Call{Call: _e.mock.On("ListSyncConflicts", ctx, branchIDs)}
}

func (_c *MockRepository_ListSyncConflicts_Call) Run(run func(ctx context.Context, branchIDs []uint)) *MockRepository_ListSyncConflicts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockRepository_ListSyncConflicts_Call) Return(_a0 []SyncConflict, _a1 error) *MockRepository_ListSyncConflicts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListSyncConflicts_Call) RunAndReturn(run func(context.Context, []uint) ([]SyncConflict, error)) *MockRepository_ListSyncConflicts_Call {
	_c.Call.Return(run)
	return _c
}

// UnresolvedConflictCount provides a mock function with given fields: ctx, branchIDs
func (_m *MockRepository) UnresolvedConflictCount(ctx context.Context, branchIDs []uint) (int64, error) {
	ret := _m.Called(ctx, branchIDs)

	if len(ret) == 0 {
		panic("no return value specified for UnresolvedConflictCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) (int64, error)); ok {
		return rf(ctx, branchIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint) int64); ok {
		r0 = rf(ctx, branchIDs)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = rf(ctx, branchIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UnresolvedConflictCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnresolvedConflictCount'
type MockRepository_UnresolvedConflictCount_Call struct {
	*mock.Call
}

// UnresolvedConflictCount is a helper method to define mock.On call
//   - ctx context.Context
//   - branchIDs []uint
func (_e *MockRepository_Expecter) UnresolvedConflictCount(ctx interface{}, branchIDs interface{}) *MockRepository_UnresolvedConflictCount_Call {
	return &MockRepository_UnresolvedConflictCount_Call{Call: _e.mock.On("UnresolvedConflictCount", ctx, branchIDs)}
}

func (_c *MockRepository_UnresolvedConflictCount_Call) Run(run func(ctx context.Context, branchIDs []uint)) *MockRepository_UnresolvedConflictCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockRepository_UnresolvedConflictCount_Call) Return(_a0 int64, _a1 error) *MockRepository_UnresolvedConflictCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UnresolvedConflictCount_Call) RunAndReturn(run func(context.Context, []uint) (int64, error)) *MockRepository_UnresolvedConflictCount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSyncConflictResolved provides a mock function with given fields: db, id, resolvedBy, resolvedAt
func (_m *MockRepository) UpdateSyncConflictResolved(db *gorm.DB, id uint, resolvedBy uint, resolvedAt time.Time) error {
	ret := _m.Called(db, id, resolvedBy, resolvedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSyncConflictResolved")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, uint, time.Time) error); ok {
		r0 = rf(db, id, resolvedBy, resolvedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateSyncConflictResolved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSyncConflictResolved'
type MockRepository_UpdateSyncConflictResolved_Call struct {
	*mock.Call
}

// UpdateSyncConflictResolved is a helper method to define mock.On call
//   - db *gorm.DB
//   - id uint
//   - resolvedBy uint
//   - resolvedAt time.Time
func (_e *MockRepository_Expecter) UpdateSyncConflictResolved(db interface{}, id interface{}, resolvedBy interface{}, resolvedAt interface{}) *MockRepository_UpdateSyncConflictResolved_Call {
	return &MockRepository_UpdateSyncConflictResolved_Call{Call: _e.mock.On("UpdateSyncConflictResolved", db, id, resolvedBy, resolvedAt)}
}

func (_c *MockRepository_UpdateSyncConflictResolved_Call) Run(run func(db *gorm.DB, id uint, resolvedBy uint, resolvedAt time.Time)) *MockRepository_UpdateSyncConflictResolved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint), args[2].(uint), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepository_UpdateSyncConflictResolved_Call) Return(_a0 error) *MockRepository_UpdateSyncConflictResolved_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateSyncConflictResolved_Call) RunAndReturn(run func(*gorm.DB, uint, uint, time.Time) error) *MockRepository_UpdateSyncConflictResolved_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
