// Code generated by mockery v2.53.3. DO NOT EDIT.

package datasync

import (
	context "context"
	identity "shagan_pos/internal/identity"

	mock "github.com/stretchr/testify/mock"
)

// MockStaffLookup is an autogenerated mock type for the StaffLookup type
type MockStaffLookup struct {
	mock.Mock
}

type MockStaffLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStaffLookup) EXPECT() *MockStaffLookup_Expecter {
	return &MockStaffLookup_Expecter{mock: &_m.Mock}
}

// GetStaff provides a mock function with given fields: ctx, orgID, id
func (_m *MockStaffLookup) GetStaff(ctx context.Context, orgID uint, id uint) (*identity.Staff, error) {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetStaff")
	}

	var r0 *identity.Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*identity.Staff, error)); ok {
		return rf(ctx, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *identity.Staff); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStaffLookup_GetStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStaff'
type MockStaffLookup_GetStaff_Call struct {
	*mock.Call
}

// GetStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - id uint
func (_e *MockStaffLookup_Expecter) GetStaff(ctx interface{}, orgID interface{}, id interface{}) *MockStaffLookup_GetStaff_Call {
	return &MockStaffLookup_GetStaff_Call{Call: _e.mock.On("GetStaff", ctx, orgID, id)}
}

func (_c *MockStaffLookup_GetStaff_Call) Run(run func(ctx context.Context, orgID uint, id uint)) *MockStaffLookup_GetStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockStaffLookup_GetStaff_Call) Return(_a0 *identity.Staff, _a1 error) *MockStaffLookup_GetStaff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStaffLookup_GetStaff_Call) RunAndReturn(run func(context.Context, uint, uint) (*identity.Staff, error)) *MockStaffLookup_GetStaff_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStaffLookup creates a new instance of MockStaffLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStaffLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStaffLookup {
	mock := &MockStaffLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
