// Code generated by mockery v2.53.3. DO NOT EDIT.

package datasync

import (
	context "context"
	sales "shagan_pos/internal/sales"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSalesWriter is an autogenerated mock type for the SalesWriter type
type MockSalesWriter struct {
	mock.Mock
}

type MockSalesWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSalesWriter) EXPECT() *MockSalesWriter_Expecter {
	return &MockSalesWriter_Expecter{mock: &_m.Mock}
}

// CreateSale provides a mock function with given fields: ctx, orgID, branchID, actor, in, allowNegativeStock
func (_m *MockSalesWriter) CreateSale(ctx context.Context, orgID uint, branchID uint, actor sales.SaleActor, in sales.CreateSaleRequest, allowNegativeStock bool) (*sales.Sale, []sales.NegativeStockEvent, error) {
	ret := _m.Called(ctx, orgID, branchID, actor, in, allowNegativeStock)

	if len(ret) == 0 {
		panic("no return value specified for CreateSale")
	}

	var r0 *sales.Sale
	var r1 []sales.NegativeStockEvent
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, sales.SaleActor, sales.CreateSaleRequest, bool) (*sales.Sale, []sales.NegativeStockEvent, error)); ok {
		return rf(ctx, orgID, branchID, actor, in, allowNegativeStock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, sales.SaleActor, sales.CreateSaleRequest, bool) *sales.Sale); ok {
		r0 = rf(ctx, orgID, branchID, actor, in, allowNegativeStock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sales.Sale)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, sales.SaleActor, sales.CreateSaleRequest, bool) []sales.NegativeStockEvent); ok {
		r1 = rf(ctx, orgID, branchID, actor, in, allowNegativeStock)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]sales.NegativeStockEvent)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, uint, sales.SaleActor, sales.CreateSaleRequest, bool) error); ok {
		r2 = rf(ctx, orgID, branchID, actor, in, allowNegativeStock)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSalesWriter_CreateSale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSale'
type MockSalesWriter_CreateSale_Call struct {
	*mock.Call
}

// CreateSale is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID uint
//   - actor sales.SaleActor
//   - in sales.CreateSaleRequest
//   - allowNegativeStock bool
func (_e *MockSalesWriter_Expecter) CreateSale(ctx interface{}, orgID interface{}, branchID interface{}, actor interface{}, in interface{}, allowNegativeStock interface{}) *MockSalesWriter_CreateSale_Call {
	return &MockSalesWriter_CreateSale_Call{Call: _e.mock.On("CreateSale", ctx, orgID, branchID, actor, in, allowNegativeStock)}
}

func (_c *MockSalesWriter_CreateSale_Call) Run(run func(ctx context.Context, orgID uint, branchID uint, actor sales.SaleActor, in sales.CreateSaleRequest, allowNegativeStock bool)) *MockSalesWriter_CreateSale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(sales.SaleActor), args[4].(sales.CreateSaleRequest), args[5].(bool))
	})
	return _c
}

func (_c *MockSalesWriter_CreateSale_Call) Return(_a0 *sales.Sale, _a1 []sales.NegativeStockEvent, _a2 error) *MockSalesWriter_CreateSale_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSalesWriter_CreateSale_Call) RunAndReturn(run func(context.Context, uint, uint, sales.SaleActor, sales.CreateSaleRequest, bool) (*sales.Sale, []sales.NegativeStockEvent, error)) *MockSalesWriter_CreateSale_Call {
	_c.Call.Return(run)
	return _c
}

// GetSale provides a mock function with given fields: ctx, orgID, id
func (_m *MockSalesWriter) GetSale(ctx context.Context, orgID uint, id uuid.UUID) (*sales.Sale, error) {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSale")
	}

	var r0 *sales.Sale
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uuid.UUID) (*sales.Sale, error)); ok {
		return rf(ctx, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uuid.UUID) *sales.Sale); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sales.Sale)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSalesWriter_GetSale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSale'
type MockSalesWriter_GetSale_Call struct {
	*mock.Call
}

// GetSale is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - id uuid.UUID
func (_e *MockSalesWriter_Expecter) GetSale(ctx interface{}, orgID interface{}, id interface{}) *MockSalesWriter_GetSale_Call {
	return &MockSalesWriter_GetSale_Call{Call: _e.mock.On("GetSale", ctx, orgID, id)}
}

func (_c *MockSalesWriter_GetSale_Call) Run(run func(ctx context.Context, orgID uint, id uuid.UUID)) *MockSalesWriter_GetSale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockSalesWriter_GetSale_Call) Return(_a0 *sales.Sale, _a1 error) *MockSalesWriter_GetSale_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSalesWriter_GetSale_Call) RunAndReturn(run func(context.Context, uint, uuid.UUID) (*sales.Sale, error)) *MockSalesWriter_GetSale_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSalesWriter creates a new instance of MockSalesWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSalesWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSalesWriter {
	mock := &MockSalesWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
