// Code generated by mockery v2.53.3. DO NOT EDIT.

package procurement

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateGoodsReceipt provides a mock function with given fields: ctx, id, in
func (_m *MockRepository) CreateGoodsReceipt(ctx context.Context, id uint, in CreateGoodsReceiptRequest) (*GoodsReceipt, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateGoodsReceipt")
	}

	var r0 *GoodsReceipt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, CreateGoodsReceiptRequest) (*GoodsReceipt, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, CreateGoodsReceiptRequest) *GoodsReceipt); ok {
		r0 = rf(ctx, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GoodsReceipt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, CreateGoodsReceiptRequest) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateGoodsReceipt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGoodsReceipt'
type MockRepository_CreateGoodsReceipt_Call struct {
	*mock.Call
}

// CreateGoodsReceipt is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - in CreateGoodsReceiptRequest
func (_e *MockRepository_Expecter) CreateGoodsReceipt(ctx interface{}, id interface{}, in interface{}) *MockRepository_CreateGoodsReceipt_Call {
	return &MockRepository_CreateGoodsReceipt_Call{Call: _e.mock.On("CreateGoodsReceipt", ctx, id, in)}
}

func (_c *MockRepository_CreateGoodsReceipt_Call) Run(run func(ctx context.Context, id uint, in CreateGoodsReceiptRequest)) *MockRepository_CreateGoodsReceipt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(CreateGoodsReceiptRequest))
	})
	return _c
}

func (_c *MockRepository_CreateGoodsReceipt_Call) Return(_a0 *GoodsReceipt, _a1 error) *MockRepository_CreateGoodsReceipt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateGoodsReceipt_Call) RunAndReturn(run func(context.Context, uint, CreateGoodsReceiptRequest) (*GoodsReceipt, error)) *MockRepository_CreateGoodsReceipt_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePurchaseOrder provides a mock function with given fields: ctx, in
func (_m *MockRepository) CreatePurchaseOrder(ctx context.Context, in CreatePurchaseOrderRequest) (*PurchaseOrder, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreatePurchaseOrder")
	}

	var r0 *PurchaseOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, CreatePurchaseOrderRequest) (*PurchaseOrder, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, CreatePurchaseOrderRequest) *PurchaseOrder); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PurchaseOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, CreatePurchaseOrderRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreatePurchaseOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePurchaseOrder'
type MockRepository_CreatePurchaseOrder_Call struct {
	*mock.Call
}

// CreatePurchaseOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in CreatePurchaseOrderRequest
func (_e *MockRepository_Expecter) CreatePurchaseOrder(ctx interface{}, in interface{}) *MockRepository_CreatePurchaseOrder_Call {
	return &MockRepository_CreatePurchaseOrder_Call{Call: _e.mock.On("CreatePurchaseOrder", ctx, in)}
}

func (_c *MockRepository_CreatePurchaseOrder_Call) Run(run func(ctx context.Context, in CreatePurchaseOrderRequest)) *MockRepository_CreatePurchaseOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(CreatePurchaseOrderRequest))
	})
	return _c
}

func (_c *MockRepository_CreatePurchaseOrder_Call) Return(_a0 *PurchaseOrder, _a1 error) *MockRepository_CreatePurchaseOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreatePurchaseOrder_Call) RunAndReturn(run func(context.Context, CreatePurchaseOrderRequest) (*PurchaseOrder, error)) *MockRepository_CreatePurchaseOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSupplier provides a mock function with given fields: ctx, supplier
func (_m *MockRepository) CreateSupplier(ctx context.Context, supplier *Supplier) error {
	ret := _m.Called(ctx, supplier)

	if len(ret) == 0 {
		panic("no return value specified for CreateSupplier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Supplier) error); ok {
		r0 = rf(ctx, supplier)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateSupplier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSupplier'
type MockRepository_CreateSupplier_Call struct {
	*mock.Call
}

// CreateSupplier is a helper method to define mock.On call
//   - ctx context.Context
//   - supplier *Supplier
func (_e *MockRepository_Expecter) CreateSupplier(ctx interface{}, supplier interface{}) *MockRepository_CreateSupplier_Call {
	return &MockRepository_CreateSupplier_Call{Call: _e.mock.On("CreateSupplier", ctx, supplier)}
}

func (_c *MockRepository_CreateSupplier_Call) Run(run func(ctx context.Context, supplier *Supplier)) *MockRepository_CreateSupplier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Supplier))
	})
	return _c
}

func (_c *MockRepository_CreateSupplier_Call) Return(_a0 error) *MockRepository_CreateSupplier_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateSupplier_Call) RunAndReturn(run func(context.Context, *Supplier) error) *MockRepository_CreateSupplier_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSupplier provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteSupplier(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSupplier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteSupplier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSupplier'
type MockRepository_DeleteSupplier_Call struct {
	*mock.Call
}

// DeleteSupplier is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRepository_Expecter) DeleteSupplier(ctx interface{}, id interface{}) *MockRepository_DeleteSupplier_Call {
	return &MockRepository_DeleteSupplier_Call{Call: _e.mock.On("DeleteSupplier", ctx, id)}
}

func (_c *MockRepository_DeleteSupplier_Call) Run(run func(ctx context.Context, id uint)) *MockRepository_DeleteSupplier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_DeleteSupplier_Call) Return(_a0 error) *MockRepository_DeleteSupplier_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteSupplier_Call) RunAndReturn(run func(context.Context, uint) error) *MockRepository_DeleteSupplier_Call {
	_c.Call.Return(run)
	return _c
}

// GetPurchaseOrder provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetPurchaseOrder(ctx context.Context, id uint) (*PurchaseOrder, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPurchaseOrder")
	}

	var r0 *PurchaseOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*PurchaseOrder, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *PurchaseOrder); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PurchaseOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetPurchaseOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPurchaseOrder'
type MockRepository_GetPurchaseOrder_Call struct {
	*mock.Call
}

// GetPurchaseOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRepository_Expecter) GetPurchaseOrder(ctx interface{}, id interface{}) *MockRepository_GetPurchaseOrder_Call {
	return &MockRepository_GetPurchaseOrder_Call{Call: _e.mock.On("GetPurchaseOrder", ctx, id)}
}

func (_c *MockRepository_GetPurchaseOrder_Call) Run(run func(ctx context.Context, id uint)) *MockRepository_GetPurchaseOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_GetPurchaseOrder_Call) Return(_a0 *PurchaseOrder, _a1 error) *MockRepository_GetPurchaseOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetPurchaseOrder_Call) RunAndReturn(run func(context.Context, uint) (*PurchaseOrder, error)) *MockRepository_GetPurchaseOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetSupplier provides a mock function with given fields: ctx, orgID, id
func (_m *MockRepository) GetSupplier(ctx context.Context, orgID uint, id uint) (*Supplier, error) {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSupplier")
	}

	var r0 *Supplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*Supplier, error)); ok {
		return rf(ctx, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *Supplier); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetSupplier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSupplier'
type MockRepository_GetSupplier_Call struct {
	*mock.Call
}

// GetSupplier is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - id uint
func (_e *MockRepository_Expecter) GetSupplier(ctx interface{}, orgID interface{}, id interface{}) *MockRepository_GetSupplier_Call {
	return &MockRepository_GetSupplier_Call{Call: _e.mock.On("GetSupplier", ctx, orgID, id)}
}

func (_c *MockRepository_GetSupplier_Call) Run(run func(ctx context.Context, orgID uint, id uint)) *MockRepository_GetSupplier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockRepository_GetSupplier_Call) Return(_a0 *Supplier, _a1 error) *MockRepository_GetSupplier_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetSupplier_Call) RunAndReturn(run func(context.Context, uint, uint) (*Supplier, error)) *MockRepository_GetSupplier_Call {
	_c.Call.Return(run)
	return _c
}

// ListPurchaseOrders provides a mock function with given fields: ctx
func (_m *MockRepository) ListPurchaseOrders(ctx context.Context) ([]PurchaseOrder, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPurchaseOrders")
	}

	var r0 []PurchaseOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]PurchaseOrder, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []PurchaseOrder); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PurchaseOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListPurchaseOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPurchaseOrders'
type MockRepository_ListPurchaseOrders_Call struct {
	*mock.Call
}

// ListPurchaseOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListPurchaseOrders(ctx interface{}) *MockRepository_ListPurchaseOrders_Call {
	return &MockRepository_ListPurchaseOrders_Call{Call: _e.mock.On("ListPurchaseOrders", ctx)}
}

func (_c *MockRepository_ListPurchaseOrders_Call) Run(run func(ctx context.Context)) *MockRepository_ListPurchaseOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListPurchaseOrders_Call) Return(_a0 []PurchaseOrder, _a1 error) *MockRepository_ListPurchaseOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListPurchaseOrders_Call) RunAndReturn(run func(context.Context) ([]PurchaseOrder, error)) *MockRepository_ListPurchaseOrders_Call {
	_c.Call.Return(run)
	return _c
}

// ListSuppliers provides a mock function with given fields: ctx, orgID
func (_m *MockRepository) ListSuppliers(ctx context.Context, orgID uint) ([]Supplier, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListSuppliers")
	}

	var r0 []Supplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]Supplier, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []Supplier); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListSuppliers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSuppliers'
type MockRepository_ListSuppliers_Call struct {
	*mock.Call
}

// ListSuppliers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
func (_e *MockRepository_Expecter) ListSuppliers(ctx interface{}, orgID interface{}) *MockRepository_ListSuppliers_Call {
	return &MockRepository_ListSuppliers_Call{Call: _e.mock.On("ListSuppliers", ctx, orgID)}
}

func (_c *MockRepository_ListSuppliers_Call) Run(run func(ctx context.Context, orgID uint)) *MockRepository_ListSuppliers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_ListSuppliers_Call) Return(_a0 []Supplier, _a1 error) *MockRepository_ListSuppliers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListSuppliers_Call) RunAndReturn(run func(context.Context, uint) ([]Supplier, error)) *MockRepository_ListSuppliers_Call {
	_c.Call.Return(run)
	return _c
}

// PurchaseOrdersExistForSupplier provides a mock function with given fields: ctx, supplierID
func (_m *MockRepository) PurchaseOrdersExistForSupplier(ctx context.Context, supplierID uint) (bool, error) {
	ret := _m.Called(ctx, supplierID)

	if len(ret) == 0 {
		panic("no return value specified for PurchaseOrdersExistForSupplier")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (bool, error)); ok {
		return rf(ctx, supplierID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) bool); ok {
		r0 = rf(ctx, supplierID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, supplierID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_PurchaseOrdersExistForSupplier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurchaseOrdersExistForSupplier'
type MockRepository_PurchaseOrdersExistForSupplier_Call struct {
	*mock.Call
}

// PurchaseOrdersExistForSupplier is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uint
func (_e *MockRepository_Expecter) PurchaseOrdersExistForSupplier(ctx interface{}, supplierID interface{}) *MockRepository_PurchaseOrdersExistForSupplier_Call {
	return &MockRepository_PurchaseOrdersExistForSupplier_Call{Call: _e.mock.On("PurchaseOrdersExistForSupplier", ctx, supplierID)}
}

func (_c *MockRepository_PurchaseOrdersExistForSupplier_Call) Run(run func(ctx context.Context, supplierID uint)) *MockRepository_PurchaseOrdersExistForSupplier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_PurchaseOrdersExistForSupplier_Call) Return(_a0 bool, _a1 error) *MockRepository_PurchaseOrdersExistForSupplier_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_PurchaseOrdersExistForSupplier_Call) RunAndReturn(run func(context.Context, uint) (bool, error)) *MockRepository_PurchaseOrdersExistForSupplier_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePurchaseOrder provides a mock function with given fields: ctx, id, in
func (_m *MockRepository) UpdatePurchaseOrder(ctx context.Context, id uint, in UpdatePurchaseOrderRequest) (*PurchaseOrder, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePurchaseOrder")
	}

	var r0 *PurchaseOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, UpdatePurchaseOrderRequest) (*PurchaseOrder, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, UpdatePurchaseOrderRequest) *PurchaseOrder); ok {
		r0 = rf(ctx, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PurchaseOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, UpdatePurchaseOrderRequest) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdatePurchaseOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePurchaseOrder'
type MockRepository_UpdatePurchaseOrder_Call struct {
	*mock.Call
}

// UpdatePurchaseOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - in UpdatePurchaseOrderRequest
func (_e *MockRepository_Expecter) UpdatePurchaseOrder(ctx interface{}, id interface{}, in interface{}) *MockRepository_UpdatePurchaseOrder_Call {
	return &MockRepository_UpdatePurchaseOrder_Call{Call: _e.mock.On("UpdatePurchaseOrder", ctx, id, in)}
}

func (_c *MockRepository_UpdatePurchaseOrder_Call) Run(run func(ctx context.Context, id uint, in UpdatePurchaseOrderRequest)) *MockRepository_UpdatePurchaseOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(UpdatePurchaseOrderRequest))
	})
	return _c
}

func (_c *MockRepository_UpdatePurchaseOrder_Call) Return(_a0 *PurchaseOrder, _a1 error) *MockRepository_UpdatePurchaseOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdatePurchaseOrder_Call) RunAndReturn(run func(context.Context, uint, UpdatePurchaseOrderRequest) (*PurchaseOrder, error)) *MockRepository_UpdatePurchaseOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSupplier provides a mock function with given fields: ctx, id, updates
func (_m *MockRepository) UpdateSupplier(ctx context.Context, id uint, updates map[string]interface{}) error {
	ret := _m.Called(ctx, id, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSupplier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, map[string]interface{}) error); ok {
		r0 = rf(ctx, id, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateSupplier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSupplier'
type MockRepository_UpdateSupplier_Call struct {
	*mock.Call
}

// UpdateSupplier is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - updates map[string]interface{}
func (_e *MockRepository_Expecter) UpdateSupplier(ctx interface{}, id interface{}, updates interface{}) *MockRepository_UpdateSupplier_Call {
	return &MockRepository_UpdateSupplier_Call{Call: _e.mock.On("UpdateSupplier", ctx, id, updates)}
}

func (_c *MockRepository_UpdateSupplier_Call) Run(run func(ctx context.Context, id uint, updates map[string]interface{})) *MockRepository_UpdateSupplier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockRepository_UpdateSupplier_Call) Return(_a0 error) *MockRepository_UpdateSupplier_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateSupplier_Call) RunAndReturn(run func(context.Context, uint, map[string]interface{}) error) *MockRepository_UpdateSupplier_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
