// Code generated by mockery v2.53.3. DO NOT EDIT.

package procurement

import (
	context "context"
	catalog "shagan_pos/internal/catalog"

	mock "github.com/stretchr/testify/mock"
)

// MockProductLookup is an autogenerated mock type for the ProductLookup type
type MockProductLookup struct {
	mock.Mock
}

type MockProductLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductLookup) EXPECT() *MockProductLookup_Expecter {
	return &MockProductLookup_Expecter{mock: &_m.Mock}
}

// GetProduct provides a mock function with given fields: ctx, orgID, id
func (_m *MockProductLookup) GetProduct(ctx context.Context, orgID uint, id uint) (*catalog.Product, error) {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *catalog.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*catalog.Product, error)); ok {
		return rf(ctx, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *catalog.Product); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*catalog.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductLookup_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type MockProductLookup_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - id uint
func (_e *MockProductLookup_Expecter) GetProduct(ctx interface{}, orgID interface{}, id interface{}) *MockProductLookup_GetProduct_Call {
	return &MockProductLookup_GetProduct_Call{Call: _e.mock.On("GetProduct", ctx, orgID, id)}
}

func (_c *MockProductLookup_GetProduct_Call) Run(run func(ctx context.Context, orgID uint, id uint)) *MockProductLookup_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockProductLookup_GetProduct_Call) Return(_a0 *catalog.Product, _a1 error) *MockProductLookup_GetProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductLookup_GetProduct_Call) RunAndReturn(run func(context.Context, uint, uint) (*catalog.Product, error)) *MockProductLookup_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductLookup creates a new instance of MockProductLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductLookup {
	mock := &MockProductLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
