// Code generated by mockery v2.53.3. DO NOT EDIT.

package catalog

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockStorage) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorage_Expecter) Delete(ctx interface{}, key interface{}) *MockStorage_Delete_Call {
	return &MockStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockStorage_Delete_Call) Run(run func(ctx context.Context, key string)) *MockStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Delete_Call) Return(_a0 error) *MockStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// PresignedURL provides a mock function with given fields: ctx, key, expiry
func (_m *MockStorage) PresignedURL(ctx context.Context, key string, expiry time.Duration) (string, error) {
	ret := _m.Called(ctx, key, expiry)

	if len(ret) == 0 {
		panic("no return value specified for PresignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return rf(ctx, key, expiry)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = rf(ctx, key, expiry)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, key, expiry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_PresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignedURL'
type MockStorage_PresignedURL_Call struct {
	*mock.Call
}

// PresignedURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - expiry time.Duration
func (_e *MockStorage_Expecter) PresignedURL(ctx interface{}, key interface{}, expiry interface{}) *MockStorage_PresignedURL_Call {
	return &MockStorage_PresignedURL_Call{Call: _e.mock.On("PresignedURL", ctx, key, expiry)}
}

func (_c *MockStorage_PresignedURL_Call) Run(run func(ctx context.Context, key string, expiry time.Duration)) *MockStorage_PresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockStorage_PresignedURL_Call) Return(_a0 string, _a1 error) *MockStorage_PresignedURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_PresignedURL_Call) RunAndReturn(run func(context.Context, string, time.Duration) (string, error)) *MockStorage_PresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, key, reader, size, contentType
func (_m *MockStorage) Upload(ctx context.Context, key string, reader io.Reader, size int64, contentType string) error {
	ret := _m.Called(ctx, key, reader, size, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) error); ok {
		r0 = rf(ctx, key, reader, size, contentType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockStorage_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - reader io.Reader
//   - size int64
//   - contentType string
func (_e *MockStorage_Expecter) Upload(ctx interface{}, key interface{}, reader interface{}, size interface{}, contentType interface{}) *MockStorage_Upload_Call {
	return &MockStorage_Upload_Call{Call: _e.mock.On("Upload", ctx, key, reader, size, contentType)}
}

func (_c *MockStorage_Upload_Call) Run(run func(ctx context.Context, key string, reader io.Reader, size int64, contentType string)) *MockStorage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *MockStorage_Upload_Call) Return(_a0 error) *MockStorage_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader, int64, string) error) *MockStorage_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
