// Code generated by mockery v2.53.3. DO NOT EDIT.

package catalog

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateCategory provides a mock function with given fields: ctx, category
func (_m *MockRepository) CreateCategory(ctx context.Context, category *Category) error {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Category) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type MockRepository_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - category *Category
func (_e *MockRepository_Expecter) CreateCategory(ctx interface{}, category interface{}) *MockRepository_CreateCategory_Call {
	return &MockRepository_CreateCategory_Call{Call: _e.mock.On("CreateCategory", ctx, category)}
}

func (_c *MockRepository_CreateCategory_Call) Run(run func(ctx context.Context, category *Category)) *MockRepository_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Category))
	})
	return _c
}

func (_c *MockRepository_CreateCategory_Call) Return(_a0 error) *MockRepository_CreateCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateCategory_Call) RunAndReturn(run func(context.Context, *Category) error) *MockRepository_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCombo provides a mock function with given fields: db, combo
func (_m *MockRepository) CreateCombo(db *gorm.DB, combo *Combo) error {
	ret := _m.Called(db, combo)

	if len(ret) == 0 {
		panic("no return value specified for CreateCombo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *Combo) error); ok {
		r0 = rf(db, combo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateCombo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCombo'
type MockRepository_CreateCombo_Call struct {
	*mock.Call
}

// CreateCombo is a helper method to define mock.On call
//   - db *gorm.DB
//   - combo *Combo
func (_e *MockRepository_Expecter) CreateCombo(db interface{}, combo interface{}) *MockRepository_CreateCombo_Call {
	return &MockRepository_CreateCombo_Call{Call: _e.mock.On("CreateCombo", db, combo)}
}

func (_c *MockRepository_CreateCombo_Call) Run(run func(db *gorm.DB, combo *Combo)) *MockRepository_CreateCombo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*Combo))
	})
	return _c
}

func (_c *MockRepository_CreateCombo_Call) Return(_a0 error) *MockRepository_CreateCombo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateCombo_Call) RunAndReturn(run func(*gorm.DB, *Combo) error) *MockRepository_CreateCombo_Call {
	_c.Call.Return(run)
	return _c
}

// CreateComboImage provides a mock function with given fields: db, image
func (_m *MockRepository) CreateComboImage(db *gorm.DB, image *ComboImage) error {
	ret := _m.Called(db, image)

	if len(ret) == 0 {
		panic("no return value specified for CreateComboImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *ComboImage) error); ok {
		r0 = rf(db, image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateComboImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComboImage'
type MockRepository_CreateComboImage_Call struct {
	*mock.Call
}

// CreateComboImage is a helper method to define mock.On call
//   - db *gorm.DB
//   - image *ComboImage
func (_e *MockRepository_Expecter) CreateComboImage(db interface{}, image interface{}) *MockRepository_CreateComboImage_Call {
	return &MockRepository_CreateComboImage_Call{Call: _e.mock.On("CreateComboImage", db, image)}
}

func (_c *MockRepository_CreateComboImage_Call) Run(run func(db *gorm.DB, image *ComboImage)) *MockRepository_CreateComboImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*ComboImage))
	})
	return _c
}

func (_c *MockRepository_CreateComboImage_Call) Return(_a0 error) *MockRepository_CreateComboImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateComboImage_Call) RunAndReturn(run func(*gorm.DB, *ComboImage) error) *MockRepository_CreateComboImage_Call {
	_c.Call.Return(run)
	return _c
}

// CreateComboItems provides a mock function with given fields: db, items
func (_m *MockRepository) CreateComboItems(db *gorm.DB, items []ComboItem) error {
	ret := _m.Called(db, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateComboItems")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, []ComboItem) error); ok {
		r0 = rf(db, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateComboItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComboItems'
type MockRepository_CreateComboItems_Call struct {
	*mock.Call
}

// CreateComboItems is a helper method to define mock.On call
//   - db *gorm.DB
//   - items []ComboItem
func (_e *MockRepository_Expecter) CreateComboItems(db interface{}, items interface{}) *MockRepository_CreateComboItems_Call {
	return &MockRepository_CreateComboItems_Call{Call: _e.mock.On("CreateComboItems", db, items)}
}

func (_c *MockRepository_CreateComboItems_Call) Run(run func(db *gorm.DB, items []ComboItem)) *MockRepository_CreateComboItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].([]ComboItem))
	})
	return _c
}

func (_c *MockRepository_CreateComboItems_Call) Return(_a0 error) *MockRepository_CreateComboItems_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateComboItems_Call) RunAndReturn(run func(*gorm.DB, []ComboItem) error) *MockRepository_CreateComboItems_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProduct provides a mock function with given fields: db, product
func (_m *MockRepository) CreateProduct(db *gorm.DB, product *Product) error {
	ret := _m.Called(db, product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *Product) error); ok {
		r0 = rf(db, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type MockRepository_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - db *gorm.DB
//   - product *Product
func (_e *MockRepository_Expecter) CreateProduct(db interface{}, product interface{}) *MockRepository_CreateProduct_Call {
	return &MockRepository_CreateProduct_Call{Call: _e.mock.On("CreateProduct", db, product)}
}

func (_c *MockRepository_CreateProduct_Call) Run(run func(db *gorm.DB, product *Product)) *MockRepository_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*Product))
	})
	return _c
}

func (_c *MockRepository_CreateProduct_Call) Return(_a0 error) *MockRepository_CreateProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateProduct_Call) RunAndReturn(run func(*gorm.DB, *Product) error) *MockRepository_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProductImage provides a mock function with given fields: db, image
func (_m *MockRepository) CreateProductImage(db *gorm.DB, image *ProductImage) error {
	ret := _m.Called(db, image)

	if len(ret) == 0 {
		panic("no return value specified for CreateProductImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *ProductImage) error); ok {
		r0 = rf(db, image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateProductImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProductImage'
type MockRepository_CreateProductImage_Call struct {
	*mock.Call
}

// CreateProductImage is a helper method to define mock.On call
//   - db *gorm.DB
//   - image *ProductImage
func (_e *MockRepository_Expecter) CreateProductImage(db interface{}, image interface{}) *MockRepository_CreateProductImage_Call {
	return &MockRepository_CreateProductImage_Call{Call: _e.mock.On("CreateProductImage", db, image)}
}

func (_c *MockRepository_CreateProductImage_Call) Run(run func(db *gorm.DB, image *ProductImage)) *MockRepository_CreateProductImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*ProductImage))
	})
	return _c
}

func (_c *MockRepository_CreateProductImage_Call) Return(_a0 error) *MockRepository_CreateProductImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateProductImage_Call) RunAndReturn(run func(*gorm.DB, *ProductImage) error) *MockRepository_CreateProductImage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCategory provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteCategory(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCategory'
type MockRepository_DeleteCategory_Call struct {
	*mock.Call
}

// DeleteCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRepository_Expecter) DeleteCategory(ctx interface{}, id interface{}) *MockRepository_DeleteCategory_Call {
	return &MockRepository_DeleteCategory_Call{Call: _e.mock.On("DeleteCategory", ctx, id)}
}

func (_c *MockRepository_DeleteCategory_Call) Run(run func(ctx context.Context, id uint)) *MockRepository_DeleteCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_DeleteCategory_Call) Return(_a0 error) *MockRepository_DeleteCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteCategory_Call) RunAndReturn(run func(context.Context, uint) error) *MockRepository_DeleteCategory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCombo provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteCombo(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCombo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteCombo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCombo'
type MockRepository_DeleteCombo_Call struct {
	*mock.Call
}

// DeleteCombo is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRepository_Expecter) DeleteCombo(ctx interface{}, id interface{}) *MockRepository_DeleteCombo_Call {
	return &MockRepository_DeleteCombo_Call{Call: _e.mock.On("DeleteCombo", ctx, id)}
}

func (_c *MockRepository_DeleteCombo_Call) Run(run func(ctx context.Context, id uint)) *MockRepository_DeleteCombo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_DeleteCombo_Call) Return(_a0 error) *MockRepository_DeleteCombo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteCombo_Call) RunAndReturn(run func(context.Context, uint) error) *MockRepository_DeleteCombo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComboImagesByComboID provides a mock function with given fields: db, comboID
func (_m *MockRepository) DeleteComboImagesByComboID(db *gorm.DB, comboID uint) error {
	ret := _m.Called(db, comboID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComboImagesByComboID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) error); ok {
		r0 = rf(db, comboID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteComboImagesByComboID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComboImagesByComboID'
type MockRepository_DeleteComboImagesByComboID_Call struct {
	*mock.Call
}

// DeleteComboImagesByComboID is a helper method to define mock.On call
//   - db *gorm.DB
//   - comboID uint
func (_e *MockRepository_Expecter) DeleteComboImagesByComboID(db interface{}, comboID interface{}) *MockRepository_DeleteComboImagesByComboID_Call {
	return &MockRepository_DeleteComboImagesByComboID_Call{Call: _e.mock.On("DeleteComboImagesByComboID", db, comboID)}
}

func (_c *MockRepository_DeleteComboImagesByComboID_Call) Run(run func(db *gorm.DB, comboID uint)) *MockRepository_DeleteComboImagesByComboID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_DeleteComboImagesByComboID_Call) Return(_a0 error) *MockRepository_DeleteComboImagesByComboID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteComboImagesByComboID_Call) RunAndReturn(run func(*gorm.DB, uint) error) *MockRepository_DeleteComboImagesByComboID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteProduct(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type MockRepository_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRepository_Expecter) DeleteProduct(ctx interface{}, id interface{}) *MockRepository_DeleteProduct_Call {
	return &MockRepository_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, id)}
}

func (_c *MockRepository_DeleteProduct_Call) Run(run func(ctx context.Context, id uint)) *MockRepository_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_DeleteProduct_Call) Return(_a0 error) *MockRepository_DeleteProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteProduct_Call) RunAndReturn(run func(context.Context, uint) error) *MockRepository_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProductImagesByProductID provides a mock function with given fields: db, productID
func (_m *MockRepository) DeleteProductImagesByProductID(db *gorm.DB, productID uint) error {
	ret := _m.Called(db, productID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProductImagesByProductID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) error); ok {
		r0 = rf(db, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteProductImagesByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProductImagesByProductID'
type MockRepository_DeleteProductImagesByProductID_Call struct {
	*mock.Call
}

// DeleteProductImagesByProductID is a helper method to define mock.On call
//   - db *gorm.DB
//   - productID uint
func (_e *MockRepository_Expecter) DeleteProductImagesByProductID(db interface{}, productID interface{}) *MockRepository_DeleteProductImagesByProductID_Call {
	return &MockRepository_DeleteProductImagesByProductID_Call{Call: _e.mock.On("DeleteProductImagesByProductID", db, productID)}
}

func (_c *MockRepository_DeleteProductImagesByProductID_Call) Run(run func(db *gorm.DB, productID uint)) *MockRepository_DeleteProductImagesByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_DeleteProductImagesByProductID_Call) Return(_a0 error) *MockRepository_DeleteProductImagesByProductID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteProductImagesByProductID_Call) RunAndReturn(run func(*gorm.DB, uint) error) *MockRepository_DeleteProductImagesByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategory provides a mock function with given fields: ctx, orgID, id
func (_m *MockRepository) GetCategory(ctx context.Context, orgID uint, id uint) (*Category, error) {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategory")
	}

	var r0 *Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*Category, error)); ok {
		return rf(ctx, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *Category); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategory'
type MockRepository_GetCategory_Call struct {
	*mock.Call
}

// GetCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - id uint
func (_e *MockRepository_Expecter) GetCategory(ctx interface{}, orgID interface{}, id interface{}) *MockRepository_GetCategory_Call {
	return &MockRepository_GetCategory_Call{Call: _e.mock.On("GetCategory", ctx, orgID, id)}
}

func (_c *MockRepository_GetCategory_Call) Run(run func(ctx context.Context, orgID uint, id uint)) *MockRepository_GetCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockRepository_GetCategory_Call) Return(_a0 *Category, _a1 error) *MockRepository_GetCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetCategory_Call) RunAndReturn(run func(context.Context, uint, uint) (*Category, error)) *MockRepository_GetCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetCombo provides a mock function with given fields: ctx, orgID, id
func (_m *MockRepository) GetCombo(ctx context.Context, orgID uint, id uint) (*Combo, error) {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCombo")
	}

	var r0 *Combo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*Combo, error)); ok {
		return rf(ctx, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *Combo); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Combo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetCombo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCombo'
type MockRepository_GetCombo_Call struct {
	*mock.Call
}

// GetCombo is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - id uint
func (_e *MockRepository_Expecter) GetCombo(ctx interface{}, orgID interface{}, id interface{}) *MockRepository_GetCombo_Call {
	return &MockRepository_GetCombo_Call{Call: _e.mock.On("GetCombo", ctx, orgID, id)}
}

func (_c *MockRepository_GetCombo_Call) Run(run func(ctx context.Context, orgID uint, id uint)) *MockRepository_GetCombo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockRepository_GetCombo_Call) Return(_a0 *Combo, _a1 error) *MockRepository_GetCombo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetCombo_Call) RunAndReturn(run func(context.Context, uint, uint) (*Combo, error)) *MockRepository_GetCombo_Call {
	_c.Call.Return(run)
	return _c
}

// GetProduct provides a mock function with given fields: ctx, orgID, id
func (_m *MockRepository) GetProduct(ctx context.Context, orgID uint, id uint) (*Product, error) {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*Product, error)); ok {
		return rf(ctx, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *Product); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type MockRepository_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - id uint
func (_e *MockRepository_Expecter) GetProduct(ctx interface{}, orgID interface{}, id interface{}) *MockRepository_GetProduct_Call {
	return &MockRepository_GetProduct_Call{Call: _e.mock.On("GetProduct", ctx, orgID, id)}
}

func (_c *MockRepository_GetProduct_Call) Run(run func(ctx context.Context, orgID uint, id uint)) *MockRepository_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockRepository_GetProduct_Call) Return(_a0 *Product, _a1 error) *MockRepository_GetProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetProduct_Call) RunAndReturn(run func(context.Context, uint, uint) (*Product, error)) *MockRepository_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByBarcode provides a mock function with given fields: ctx, orgID, branchID, code
func (_m *MockRepository) GetProductByBarcode(ctx context.Context, orgID uint, branchID uint, code string) (*Product, error) {
	ret := _m.Called(ctx, orgID, branchID, code)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByBarcode")
	}

	var r0 *Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) (*Product, error)); ok {
		return rf(ctx, orgID, branchID, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) *Product); ok {
		r0 = rf(ctx, orgID, branchID, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, string) error); ok {
		r1 = rf(ctx, orgID, branchID, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetProductByBarcode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByBarcode'
type MockRepository_GetProductByBarcode_Call struct {
	*mock.Call
}

// GetProductByBarcode is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID uint
//   - code string
func (_e *MockRepository_Expecter) GetProductByBarcode(ctx interface{}, orgID interface{}, branchID interface{}, code interface{}) *MockRepository_GetProductByBarcode_Call {
	return &MockRepository_GetProductByBarcode_Call{Call: _e.mock.On("GetProductByBarcode", ctx, orgID, branchID, code)}
}

func (_c *MockRepository_GetProductByBarcode_Call) Run(run func(ctx context.Context, orgID uint, branchID uint, code string)) *MockRepository_GetProductByBarcode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(string))
	})
	return _c
}

func (_c *MockRepository_GetProductByBarcode_Call) Return(_a0 *Product, _a1 error) *MockRepository_GetProductByBarcode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetProductByBarcode_Call) RunAndReturn(run func(context.Context, uint, uint, string) (*Product, error)) *MockRepository_GetProductByBarcode_Call {
	_c.Call.Return(run)
	return _c
}

// ListCategories provides a mock function with given fields: ctx, orgID
func (_m *MockRepository) ListCategories(ctx context.Context, orgID uint) ([]Category, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]Category, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []Category); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type MockRepository_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
func (_e *MockRepository_Expecter) ListCategories(ctx interface{}, orgID interface{}) *MockRepository_ListCategories_Call {
	return &MockRepository_ListCategories_Call{Call: _e.mock.On("ListCategories", ctx, orgID)}
}

func (_c *MockRepository_ListCategories_Call) Run(run func(ctx context.Context, orgID uint)) *MockRepository_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_ListCategories_Call) Return(_a0 []Category, _a1 error) *MockRepository_ListCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListCategories_Call) RunAndReturn(run func(context.Context, uint) ([]Category, error)) *MockRepository_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ListComboImagesByComboID provides a mock function with given fields: ctx, comboID
func (_m *MockRepository) ListComboImagesByComboID(ctx context.Context, comboID uint) ([]ComboImage, error) {
	ret := _m.Called(ctx, comboID)

	if len(ret) == 0 {
		panic("no return value specified for ListComboImagesByComboID")
	}

	var r0 []ComboImage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]ComboImage, error)); ok {
		return rf(ctx, comboID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []ComboImage); ok {
		r0 = rf(ctx, comboID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ComboImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, comboID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListComboImagesByComboID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComboImagesByComboID'
type MockRepository_ListComboImagesByComboID_Call struct {
	*mock.Call
}

// ListComboImagesByComboID is a helper method to define mock.On call
//   - ctx context.Context
//   - comboID uint
func (_e *MockRepository_Expecter) ListComboImagesByComboID(ctx interface{}, comboID interface{}) *MockRepository_ListComboImagesByComboID_Call {
	return &MockRepository_ListComboImagesByComboID_Call{Call: _e.mock.On("ListComboImagesByComboID", ctx, comboID)}
}

func (_c *MockRepository_ListComboImagesByComboID_Call) Run(run func(ctx context.Context, comboID uint)) *MockRepository_ListComboImagesByComboID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_ListComboImagesByComboID_Call) Return(_a0 []ComboImage, _a1 error) *MockRepository_ListComboImagesByComboID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListComboImagesByComboID_Call) RunAndReturn(run func(context.Context, uint) ([]ComboImage, error)) *MockRepository_ListComboImagesByComboID_Call {
	_c.Call.Return(run)
	return _c
}

// ListCombos provides a mock function with given fields: ctx, orgID
func (_m *MockRepository) ListCombos(ctx context.Context, orgID uint) ([]Combo, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListCombos")
	}

	var r0 []Combo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]Combo, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []Combo); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Combo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListCombos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCombos'
type MockRepository_ListCombos_Call struct {
	*mock.Call
}

// ListCombos is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
func (_e *MockRepository_Expecter) ListCombos(ctx interface{}, orgID interface{}) *MockRepository_ListCombos_Call {
	return &MockRepository_ListCombos_Call{Call: _e.mock.On("ListCombos", ctx, orgID)}
}

func (_c *MockRepository_ListCombos_Call) Run(run func(ctx context.Context, orgID uint)) *MockRepository_ListCombos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_ListCombos_Call) Return(_a0 []Combo, _a1 error) *MockRepository_ListCombos_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListCombos_Call) RunAndReturn(run func(context.Context, uint) ([]Combo, error)) *MockRepository_ListCombos_Call {
	_c.Call.Return(run)
	return _c
}

// ListProductImagesByProductIDs provides a mock function with given fields: ctx, productIDs
func (_m *MockRepository) ListProductImagesByProductIDs(ctx context.Context, productIDs []uint) ([]ProductImage, error) {
	ret := _m.Called(ctx, productIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListProductImagesByProductIDs")
	}

	var r0 []ProductImage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) ([]ProductImage, error)); ok {
		return rf(ctx, productIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint) []ProductImage); ok {
		r0 = rf(ctx, productIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ProductImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = rf(ctx, productIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListProductImagesByProductIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProductImagesByProductIDs'
type MockRepository_ListProductImagesByProductIDs_Call struct {
	*mock.Call
}

// ListProductImagesByProductIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - productIDs []uint
func (_e *MockRepository_Expecter) ListProductImagesByProductIDs(ctx interface{}, productIDs interface{}) *MockRepository_ListProductImagesByProductIDs_Call {
	return &MockRepository_ListProductImagesByProductIDs_Call{Call: _e.mock.On("ListProductImagesByProductIDs", ctx, productIDs)}
}

func (_c *MockRepository_ListProductImagesByProductIDs_Call) Run(run func(ctx context.Context, productIDs []uint)) *MockRepository_ListProductImagesByProductIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockRepository_ListProductImagesByProductIDs_Call) Return(_a0 []ProductImage, _a1 error) *MockRepository_ListProductImagesByProductIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListProductImagesByProductIDs_Call) RunAndReturn(run func(context.Context, []uint) ([]ProductImage, error)) *MockRepository_ListProductImagesByProductIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ListProducts provides a mock function with given fields: ctx, orgID, branchID
func (_m *MockRepository) ListProducts(ctx context.Context, orgID uint, branchID *uint) ([]Product, error) {
	ret := _m.Called(ctx, orgID, branchID)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 []Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint) ([]Product, error)); ok {
		return rf(ctx, orgID, branchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint) []Product); ok {
		r0 = rf(ctx, orgID, branchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint) error); ok {
		r1 = rf(ctx, orgID, branchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProducts'
type MockRepository_ListProducts_Call struct {
	*mock.Call
}

// ListProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
func (_e *MockRepository_Expecter) ListProducts(ctx interface{}, orgID interface{}, branchID interface{}) *MockRepository_ListProducts_Call {
	return &MockRepository_ListProducts_Call{Call: _e.mock.On("ListProducts", ctx, orgID, branchID)}
}

func (_c *MockRepository_ListProducts_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint)) *MockRepository_ListProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint))
	})
	return _c
}

func (_c *MockRepository_ListProducts_Call) Return(_a0 []Product, _a1 error) *MockRepository_ListProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListProducts_Call) RunAndReturn(run func(context.Context, uint, *uint) ([]Product, error)) *MockRepository_ListProducts_Call {
	_c.Call.Return(run)
	return _c
}

// ProductsExistForCategory provides a mock function with given fields: ctx, categoryID
func (_m *MockRepository) ProductsExistForCategory(ctx context.Context, categoryID uint) (bool, error) {
	ret := _m.Called(ctx, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for ProductsExistForCategory")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (bool, error)); ok {
		return rf(ctx, categoryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) bool); ok {
		r0 = rf(ctx, categoryID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ProductsExistForCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProductsExistForCategory'
type MockRepository_ProductsExistForCategory_Call struct {
	*mock.Call
}

// ProductsExistForCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryID uint
func (_e *MockRepository_Expecter) ProductsExistForCategory(ctx interface{}, categoryID interface{}) *MockRepository_ProductsExistForCategory_Call {
	return &MockRepository_ProductsExistForCategory_Call{Call: _e.mock.On("ProductsExistForCategory", ctx, categoryID)}
}

func (_c *MockRepository_ProductsExistForCategory_Call) Run(run func(ctx context.Context, categoryID uint)) *MockRepository_ProductsExistForCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_ProductsExistForCategory_Call) Return(_a0 bool, _a1 error) *MockRepository_ProductsExistForCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ProductsExistForCategory_Call) RunAndReturn(run func(context.Context, uint) (bool, error)) *MockRepository_ProductsExistForCategory_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCategory provides a mock function with given fields: ctx, id, updates
func (_m *MockRepository) UpdateCategory(ctx context.Context, id uint, updates map[string]interface{}) error {
	ret := _m.Called(ctx, id, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, map[string]interface{}) error); ok {
		r0 = rf(ctx, id, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCategory'
type MockRepository_UpdateCategory_Call struct {
	*mock.Call
}

// UpdateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - updates map[string]interface{}
func (_e *MockRepository_Expecter) UpdateCategory(ctx interface{}, id interface{}, updates interface{}) *MockRepository_UpdateCategory_Call {
	return &MockRepository_UpdateCategory_Call{Call: _e.mock.On("UpdateCategory", ctx, id, updates)}
}

func (_c *MockRepository_UpdateCategory_Call) Run(run func(ctx context.Context, id uint, updates map[string]interface{})) *MockRepository_UpdateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockRepository_UpdateCategory_Call) Return(_a0 error) *MockRepository_UpdateCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateCategory_Call) RunAndReturn(run func(context.Context, uint, map[string]interface{}) error) *MockRepository_UpdateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCombo provides a mock function with given fields: db, id, updates
func (_m *MockRepository) UpdateCombo(db *gorm.DB, id uint, updates map[string]interface{}) error {
	ret := _m.Called(db, id, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCombo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, map[string]interface{}) error); ok {
		r0 = rf(db, id, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateCombo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCombo'
type MockRepository_UpdateCombo_Call struct {
	*mock.Call
}

// UpdateCombo is a helper method to define mock.On call
//   - db *gorm.DB
//   - id uint
//   - updates map[string]interface{}
func (_e *MockRepository_Expecter) UpdateCombo(db interface{}, id interface{}, updates interface{}) *MockRepository_UpdateCombo_Call {
	return &MockRepository_UpdateCombo_Call{Call: _e.mock.On("UpdateCombo", db, id, updates)}
}

func (_c *MockRepository_UpdateCombo_Call) Run(run func(db *gorm.DB, id uint, updates map[string]interface{})) *MockRepository_UpdateCombo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockRepository_UpdateCombo_Call) Return(_a0 error) *MockRepository_UpdateCombo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateCombo_Call) RunAndReturn(run func(*gorm.DB, uint, map[string]interface{}) error) *MockRepository_UpdateCombo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProduct provides a mock function with given fields: db, id, updates
func (_m *MockRepository) UpdateProduct(db *gorm.DB, id uint, updates map[string]interface{}) error {
	ret := _m.Called(db, id, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, map[string]interface{}) error); ok {
		r0 = rf(db, id, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProduct'
type MockRepository_UpdateProduct_Call struct {
	*mock.Call
}

// UpdateProduct is a helper method to define mock.On call
//   - db *gorm.DB
//   - id uint
//   - updates map[string]interface{}
func (_e *MockRepository_Expecter) UpdateProduct(db interface{}, id interface{}, updates interface{}) *MockRepository_UpdateProduct_Call {
	return &MockRepository_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", db, id, updates)}
}

func (_c *MockRepository_UpdateProduct_Call) Run(run func(db *gorm.DB, id uint, updates map[string]interface{})) *MockRepository_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockRepository_UpdateProduct_Call) Return(_a0 error) *MockRepository_UpdateProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateProduct_Call) RunAndReturn(run func(*gorm.DB, uint, map[string]interface{}) error) *MockRepository_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// UploadMedia provides a mock function with given fields: ctx
func (_m *MockRepository) UploadMedia(ctx context.Context) (*ProductImage, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UploadMedia")
	}

	var r0 *ProductImage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*ProductImage, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *ProductImage); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ProductImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UploadMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadMedia'
type MockRepository_UploadMedia_Call struct {
	*mock.Call
}

// UploadMedia is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) UploadMedia(ctx interface{}) *MockRepository_UploadMedia_Call {
	return &MockRepository_UploadMedia_Call{Call: _e.mock.On("UploadMedia", ctx)}
}

func (_c *MockRepository_UploadMedia_Call) Run(run func(ctx context.Context)) *MockRepository_UploadMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_UploadMedia_Call) Return(_a0 *ProductImage, _a1 error) *MockRepository_UploadMedia_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UploadMedia_Call) RunAndReturn(run func(context.Context) (*ProductImage, error)) *MockRepository_UploadMedia_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
