// Code generated by mockery v2.53.3. DO NOT EDIT.

package audit

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateAuditLog provides a mock function with given fields: db, entry
func (_m *MockRepository) CreateAuditLog(db *gorm.DB, entry *AuditLog) error {
	ret := _m.Called(db, entry)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuditLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *AuditLog) error); ok {
		r0 = rf(db, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateAuditLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuditLog'
type MockRepository_CreateAuditLog_Call struct {
	*mock.Call
}

// CreateAuditLog is a helper method to define mock.On call
//   - db *gorm.DB
//   - entry *AuditLog
func (_e *MockRepository_Expecter) CreateAuditLog(db interface{}, entry interface{}) *MockRepository_CreateAuditLog_Call {
	return &MockRepository_CreateAuditLog_Call{Call: _e.mock.On("CreateAuditLog", db, entry)}
}

func (_c *MockRepository_CreateAuditLog_Call) Run(run func(db *gorm.DB, entry *AuditLog)) *MockRepository_CreateAuditLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*AuditLog))
	})
	return _c
}

func (_c *MockRepository_CreateAuditLog_Call) Return(_a0 error) *MockRepository_CreateAuditLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateAuditLog_Call) RunAndReturn(run func(*gorm.DB, *AuditLog) error) *MockRepository_CreateAuditLog_Call {
	_c.Call.Return(run)
	return _c
}

// ListAuditLog provides a mock function with given fields: ctx, orgID, branchID
func (_m *MockRepository) ListAuditLog(ctx context.Context, orgID uint, branchID *uint) ([]AuditLog, error) {
	ret := _m.Called(ctx, orgID, branchID)

	if len(ret) == 0 {
		panic("no return value specified for ListAuditLog")
	}

	var r0 []AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint) ([]AuditLog, error)); ok {
		return rf(ctx, orgID, branchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint) []AuditLog); ok {
		r0 = rf(ctx, orgID, branchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint) error); ok {
		r1 = rf(ctx, orgID, branchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListAuditLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAuditLog'
type MockRepository_ListAuditLog_Call struct {
	*mock.Call
}

// ListAuditLog is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
func (_e *MockRepository_Expecter) ListAuditLog(ctx interface{}, orgID interface{}, branchID interface{}) *MockRepository_ListAuditLog_Call {
	return &MockRepository_ListAuditLog_Call{Call: _e.mock.On("ListAuditLog", ctx, orgID, branchID)}
}

func (_c *MockRepository_ListAuditLog_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint)) *MockRepository_ListAuditLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint))
	})
	return _c
}

func (_c *MockRepository_ListAuditLog_Call) Return(_a0 []AuditLog, _a1 error) *MockRepository_ListAuditLog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListAuditLog_Call) RunAndReturn(run func(context.Context, uint, *uint) ([]AuditLog, error)) *MockRepository_ListAuditLog_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
