// Code generated by mockery v2.53.3. DO NOT EDIT.

package inventory

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateInventoryLedgerEntry provides a mock function with given fields: db, entry
func (_m *MockRepository) CreateInventoryLedgerEntry(db *gorm.DB, entry *InventoryLedger) error {
	ret := _m.Called(db, entry)

	if len(ret) == 0 {
		panic("no return value specified for CreateInventoryLedgerEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *InventoryLedger) error); ok {
		r0 = rf(db, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateInventoryLedgerEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInventoryLedgerEntry'
type MockRepository_CreateInventoryLedgerEntry_Call struct {
	*mock.Call
}

// CreateInventoryLedgerEntry is a helper method to define mock.On call
//   - db *gorm.DB
//   - entry *InventoryLedger
func (_e *MockRepository_Expecter) CreateInventoryLedgerEntry(db interface{}, entry interface{}) *MockRepository_CreateInventoryLedgerEntry_Call {
	return &MockRepository_CreateInventoryLedgerEntry_Call{Call: _e.mock.On("CreateInventoryLedgerEntry", db, entry)}
}

func (_c *MockRepository_CreateInventoryLedgerEntry_Call) Run(run func(db *gorm.DB, entry *InventoryLedger)) *MockRepository_CreateInventoryLedgerEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*InventoryLedger))
	})
	return _c
}

func (_c *MockRepository_CreateInventoryLedgerEntry_Call) Return(_a0 error) *MockRepository_CreateInventoryLedgerEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateInventoryLedgerEntry_Call) RunAndReturn(run func(*gorm.DB, *InventoryLedger) error) *MockRepository_CreateInventoryLedgerEntry_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStockAdjustment provides a mock function with given fields: ctx, in
func (_m *MockRepository) CreateStockAdjustment(ctx context.Context, in CreateStockAdjustmentRequest) (*StockAdjustment, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateStockAdjustment")
	}

	var r0 *StockAdjustment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, CreateStockAdjustmentRequest) (*StockAdjustment, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, CreateStockAdjustmentRequest) *StockAdjustment); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*StockAdjustment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, CreateStockAdjustmentRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateStockAdjustment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStockAdjustment'
type MockRepository_CreateStockAdjustment_Call struct {
	*mock.Call
}

// CreateStockAdjustment is a helper method to define mock.On call
//   - ctx context.Context
//   - in CreateStockAdjustmentRequest
func (_e *MockRepository_Expecter) CreateStockAdjustment(ctx interface{}, in interface{}) *MockRepository_CreateStockAdjustment_Call {
	return &MockRepository_CreateStockAdjustment_Call{Call: _e.mock.On("CreateStockAdjustment", ctx, in)}
}

func (_c *MockRepository_CreateStockAdjustment_Call) Run(run func(ctx context.Context, in CreateStockAdjustmentRequest)) *MockRepository_CreateStockAdjustment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(CreateStockAdjustmentRequest))
	})
	return _c
}

func (_c *MockRepository_CreateStockAdjustment_Call) Return(_a0 *StockAdjustment, _a1 error) *MockRepository_CreateStockAdjustment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateStockAdjustment_Call) RunAndReturn(run func(context.Context, CreateStockAdjustmentRequest) (*StockAdjustment, error)) *MockRepository_CreateStockAdjustment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStockLevel provides a mock function with given fields: db, level
func (_m *MockRepository) CreateStockLevel(db *gorm.DB, level *StockLevel) error {
	ret := _m.Called(db, level)

	if len(ret) == 0 {
		panic("no return value specified for CreateStockLevel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *StockLevel) error); ok {
		r0 = rf(db, level)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateStockLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStockLevel'
type MockRepository_CreateStockLevel_Call struct {
	*mock.Call
}

// CreateStockLevel is a helper method to define mock.On call
//   - db *gorm.DB
//   - level *StockLevel
func (_e *MockRepository_Expecter) CreateStockLevel(db interface{}, level interface{}) *MockRepository_CreateStockLevel_Call {
	return &MockRepository_CreateStockLevel_Call{Call: _e.mock.On("CreateStockLevel", db, level)}
}

func (_c *MockRepository_CreateStockLevel_Call) Run(run func(db *gorm.DB, level *StockLevel)) *MockRepository_CreateStockLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*StockLevel))
	})
	return _c
}

func (_c *MockRepository_CreateStockLevel_Call) Return(_a0 error) *MockRepository_CreateStockLevel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateStockLevel_Call) RunAndReturn(run func(*gorm.DB, *StockLevel) error) *MockRepository_CreateStockLevel_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStockTransfer provides a mock function with given fields: ctx, in
func (_m *MockRepository) CreateStockTransfer(ctx context.Context, in CreateStockTransferRequest) (*StockTransfer, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateStockTransfer")
	}

	var r0 *StockTransfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, CreateStockTransferRequest) (*StockTransfer, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, CreateStockTransferRequest) *StockTransfer); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*StockTransfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, CreateStockTransferRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateStockTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStockTransfer'
type MockRepository_CreateStockTransfer_Call struct {
	*mock.Call
}

// CreateStockTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - in CreateStockTransferRequest
func (_e *MockRepository_Expecter) CreateStockTransfer(ctx interface{}, in interface{}) *MockRepository_CreateStockTransfer_Call {
	return &MockRepository_CreateStockTransfer_Call{Call: _e.mock.On("CreateStockTransfer", ctx, in)}
}

func (_c *MockRepository_CreateStockTransfer_Call) Run(run func(ctx context.Context, in CreateStockTransferRequest)) *MockRepository_CreateStockTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(CreateStockTransferRequest))
	})
	return _c
}

func (_c *MockRepository_CreateStockTransfer_Call) Return(_a0 *StockTransfer, _a1 error) *MockRepository_CreateStockTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateStockTransfer_Call) RunAndReturn(run func(context.Context, CreateStockTransferRequest) (*StockTransfer, error)) *MockRepository_CreateStockTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// GetStockLevel provides a mock function with given fields: db, productID, branchID
func (_m *MockRepository) GetStockLevel(db *gorm.DB, productID uint, branchID uint) (*StockLevel, error) {
	ret := _m.Called(db, productID, branchID)

	if len(ret) == 0 {
		panic("no return value specified for GetStockLevel")
	}

	var r0 *StockLevel
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, uint) (*StockLevel, error)); ok {
		return rf(db, productID, branchID)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, uint) *StockLevel); ok {
		r0 = rf(db, productID, branchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*StockLevel)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, uint, uint) error); ok {
		r1 = rf(db, productID, branchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetStockLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStockLevel'
type MockRepository_GetStockLevel_Call struct {
	*mock.Call
}

// GetStockLevel is a helper method to define mock.On call
//   - db *gorm.DB
//   - productID uint
//   - branchID uint
func (_e *MockRepository_Expecter) GetStockLevel(db interface{}, productID interface{}, branchID interface{}) *MockRepository_GetStockLevel_Call {
	return &MockRepository_GetStockLevel_Call{Call: _e.mock.On("GetStockLevel", db, productID, branchID)}
}

func (_c *MockRepository_GetStockLevel_Call) Run(run func(db *gorm.DB, productID uint, branchID uint)) *MockRepository_GetStockLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockRepository_GetStockLevel_Call) Return(_a0 *StockLevel, _a1 error) *MockRepository_GetStockLevel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetStockLevel_Call) RunAndReturn(run func(*gorm.DB, uint, uint) (*StockLevel, error)) *MockRepository_GetStockLevel_Call {
	_c.Call.Return(run)
	return _c
}

// ListInventoryLedger provides a mock function with given fields: ctx, orgID, branchID, productID
func (_m *MockRepository) ListInventoryLedger(ctx context.Context, orgID uint, branchID *uint, productID *uint) ([]InventoryLedger, error) {
	ret := _m.Called(ctx, orgID, branchID, productID)

	if len(ret) == 0 {
		panic("no return value specified for ListInventoryLedger")
	}

	var r0 []InventoryLedger
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, *uint) ([]InventoryLedger, error)); ok {
		return rf(ctx, orgID, branchID, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *uint, *uint) []InventoryLedger); ok {
		r0 = rf(ctx, orgID, branchID, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]InventoryLedger)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *uint, *uint) error); ok {
		r1 = rf(ctx, orgID, branchID, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListInventoryLedger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInventoryLedger'
type MockRepository_ListInventoryLedger_Call struct {
	*mock.Call
}

// ListInventoryLedger is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - branchID *uint
//   - productID *uint
func (_e *MockRepository_Expecter) ListInventoryLedger(ctx interface{}, orgID interface{}, branchID interface{}, productID interface{}) *MockRepository_ListInventoryLedger_Call {
	return &MockRepository_ListInventoryLedger_Call{Call: _e.mock.On("ListInventoryLedger", ctx, orgID, branchID, productID)}
}

func (_c *MockRepository_ListInventoryLedger_Call) Run(run func(ctx context.Context, orgID uint, branchID *uint, productID *uint)) *MockRepository_ListInventoryLedger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*uint), args[3].(*uint))
	})
	return _c
}

func (_c *MockRepository_ListInventoryLedger_Call) Return(_a0 []InventoryLedger, _a1 error) *MockRepository_ListInventoryLedger_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListInventoryLedger_Call) RunAndReturn(run func(context.Context, uint, *uint, *uint) ([]InventoryLedger, error)) *MockRepository_ListInventoryLedger_Call {
	_c.Call.Return(run)
	return _c
}

// ListLowStock provides a mock function with given fields: ctx
func (_m *MockRepository) ListLowStock(ctx context.Context) ([]StockLevel, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListLowStock")
	}

	var r0 []StockLevel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]StockLevel, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []StockLevel); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]StockLevel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListLowStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLowStock'
type MockRepository_ListLowStock_Call struct {
	*mock.Call
}

// ListLowStock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListLowStock(ctx interface{}) *MockRepository_ListLowStock_Call {
	return &MockRepository_ListLowStock_Call{Call: _e.mock.On("ListLowStock", ctx)}
}

func (_c *MockRepository_ListLowStock_Call) Run(run func(ctx context.Context)) *MockRepository_ListLowStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListLowStock_Call) Return(_a0 []StockLevel, _a1 error) *MockRepository_ListLowStock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListLowStock_Call) RunAndReturn(run func(context.Context) ([]StockLevel, error)) *MockRepository_ListLowStock_Call {
	_c.Call.Return(run)
	return _c
}

// ListStockLevels provides a mock function with given fields: ctx, branchIDs, productID
func (_m *MockRepository) ListStockLevels(ctx context.Context, branchIDs []uint, productID *uint) ([]StockLevel, error) {
	ret := _m.Called(ctx, branchIDs, productID)

	if len(ret) == 0 {
		panic("no return value specified for ListStockLevels")
	}

	var r0 []StockLevel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint, *uint) ([]StockLevel, error)); ok {
		return rf(ctx, branchIDs, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint, *uint) []StockLevel); ok {
		r0 = rf(ctx, branchIDs, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]StockLevel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint, *uint) error); ok {
		r1 = rf(ctx, branchIDs, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListStockLevels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStockLevels'
type MockRepository_ListStockLevels_Call struct {
	*mock.Call
}

// ListStockLevels is a helper method to define mock.On call
//   - ctx context.Context
//   - branchIDs []uint
//   - productID *uint
func (_e *MockRepository_Expecter) ListStockLevels(ctx interface{}, branchIDs interface{}, productID interface{}) *MockRepository_ListStockLevels_Call {
	return &MockRepository_ListStockLevels_Call{Call: _e.mock.On("ListStockLevels", ctx, branchIDs, productID)}
}

func (_c *MockRepository_ListStockLevels_Call) Run(run func(ctx context.Context, branchIDs []uint, productID *uint)) *MockRepository_ListStockLevels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint), args[2].(*uint))
	})
	return _c
}

func (_c *MockRepository_ListStockLevels_Call) Return(_a0 []StockLevel, _a1 error) *MockRepository_ListStockLevels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListStockLevels_Call) RunAndReturn(run func(context.Context, []uint, *uint) ([]StockLevel, error)) *MockRepository_ListStockLevels_Call {
	_c.Call.Return(run)
	return _c
}

// ListStockTransfers provides a mock function with given fields: ctx
func (_m *MockRepository) ListStockTransfers(ctx context.Context) ([]StockTransfer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListStockTransfers")
	}

	var r0 []StockTransfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]StockTransfer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []StockTransfer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]StockTransfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListStockTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStockTransfers'
type MockRepository_ListStockTransfers_Call struct {
	*mock.Call
}

// ListStockTransfers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListStockTransfers(ctx interface{}) *MockRepository_ListStockTransfers_Call {
	return &MockRepository_ListStockTransfers_Call{Call: _e.mock.On("ListStockTransfers", ctx)}
}

func (_c *MockRepository_ListStockTransfers_Call) Run(run func(ctx context.Context)) *MockRepository_ListStockTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListStockTransfers_Call) Return(_a0 []StockTransfer, _a1 error) *MockRepository_ListStockTransfers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListStockTransfers_Call) RunAndReturn(run func(context.Context) ([]StockTransfer, error)) *MockRepository_ListStockTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStockLevelQty provides a mock function with given fields: db, id, qty
func (_m *MockRepository) UpdateStockLevelQty(db *gorm.DB, id uint, qty int) error {
	ret := _m.Called(db, id, qty)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStockLevelQty")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, int) error); ok {
		r0 = rf(db, id, qty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateStockLevelQty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStockLevelQty'
type MockRepository_UpdateStockLevelQty_Call struct {
	*mock.Call
}

// UpdateStockLevelQty is a helper method to define mock.On call
//   - db *gorm.DB
//   - id uint
//   - qty int
func (_e *MockRepository_Expecter) UpdateStockLevelQty(db interface{}, id interface{}, qty interface{}) *MockRepository_UpdateStockLevelQty_Call {
	return &MockRepository_UpdateStockLevelQty_Call{Call: _e.mock.On("UpdateStockLevelQty", db, id, qty)}
}

func (_c *MockRepository_UpdateStockLevelQty_Call) Run(run func(db *gorm.DB, id uint, qty int)) *MockRepository_UpdateStockLevelQty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_UpdateStockLevelQty_Call) Return(_a0 error) *MockRepository_UpdateStockLevelQty_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateStockLevelQty_Call) RunAndReturn(run func(*gorm.DB, uint, int) error) *MockRepository_UpdateStockLevelQty_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStockTransfer provides a mock function with given fields: ctx, id, in
func (_m *MockRepository) UpdateStockTransfer(ctx context.Context, id uint, in UpdateStockTransferRequest) (*StockTransfer, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStockTransfer")
	}

	var r0 *StockTransfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, UpdateStockTransferRequest) (*StockTransfer, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, UpdateStockTransferRequest) *StockTransfer); ok {
		r0 = rf(ctx, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*StockTransfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, UpdateStockTransferRequest) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateStockTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStockTransfer'
type MockRepository_UpdateStockTransfer_Call struct {
	*mock.Call
}

// UpdateStockTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - in UpdateStockTransferRequest
func (_e *MockRepository_Expecter) UpdateStockTransfer(ctx interface{}, id interface{}, in interface{}) *MockRepository_UpdateStockTransfer_Call {
	return &MockRepository_UpdateStockTransfer_Call{Call: _e.mock.On("UpdateStockTransfer", ctx, id, in)}
}

func (_c *MockRepository_UpdateStockTransfer_Call) Run(run func(ctx context.Context, id uint, in UpdateStockTransferRequest)) *MockRepository_UpdateStockTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(UpdateStockTransferRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateStockTransfer_Call) Return(_a0 *StockTransfer, _a1 error) *MockRepository_UpdateStockTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateStockTransfer_Call) RunAndReturn(run func(context.Context, uint, UpdateStockTransferRequest) (*StockTransfer, error)) *MockRepository_UpdateStockTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
