// Code generated by mockery v2.53.3. DO NOT EDIT.

package sales

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockReturnActivityReader is an autogenerated mock type for the ReturnActivityReader type
type MockReturnActivityReader struct {
	mock.Mock
}

type MockReturnActivityReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReturnActivityReader) EXPECT() *MockReturnActivityReader_Expecter {
	return &MockReturnActivityReader_Expecter{mock: &_m.Mock}
}

// ReturnSummaries provides a mock function with given fields: ctx, saleIDs
func (_m *MockReturnActivityReader) ReturnSummaries(ctx context.Context, saleIDs []uuid.UUID) (map[uuid.UUID]ReturnSummary, error) {
	ret := _m.Called(ctx, saleIDs)

	if len(ret) == 0 {
		panic("no return value specified for ReturnSummaries")
	}

	var r0 map[uuid.UUID]ReturnSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID]ReturnSummary, error)); ok {
		return rf(ctx, saleIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID]ReturnSummary); ok {
		r0 = rf(ctx, saleIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]ReturnSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, saleIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReturnActivityReader_ReturnSummaries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReturnSummaries'
type MockReturnActivityReader_ReturnSummaries_Call struct {
	*mock.Call
}

// ReturnSummaries is a helper method to define mock.On call
//   - ctx context.Context
//   - saleIDs []uuid.UUID
func (_e *MockReturnActivityReader_Expecter) ReturnSummaries(ctx interface{}, saleIDs interface{}) *MockReturnActivityReader_ReturnSummaries_Call {
	return &MockReturnActivityReader_ReturnSummaries_Call{Call: _e.mock.On("ReturnSummaries", ctx, saleIDs)}
}

func (_c *MockReturnActivityReader_ReturnSummaries_Call) Run(run func(ctx context.Context, saleIDs []uuid.UUID)) *MockReturnActivityReader_ReturnSummaries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockReturnActivityReader_ReturnSummaries_Call) Return(_a0 map[uuid.UUID]ReturnSummary, _a1 error) *MockReturnActivityReader_ReturnSummaries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReturnActivityReader_ReturnSummaries_Call) RunAndReturn(run func(context.Context, []uuid.UUID) (map[uuid.UUID]ReturnSummary, error)) *MockReturnActivityReader_ReturnSummaries_Call {
	_c.Call.Return(run)
	return _c
}

// ReturnedQtyBySaleItems provides a mock function with given fields: ctx, saleItemIDs
func (_m *MockReturnActivityReader) ReturnedQtyBySaleItems(ctx context.Context, saleItemIDs []uint) (map[uint]int, error) {
	ret := _m.Called(ctx, saleItemIDs)

	if len(ret) == 0 {
		panic("no return value specified for ReturnedQtyBySaleItems")
	}

	var r0 map[uint]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) (map[uint]int, error)); ok {
		return rf(ctx, saleItemIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint) map[uint]int); ok {
		r0 = rf(ctx, saleItemIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = rf(ctx, saleItemIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReturnActivityReader_ReturnedQtyBySaleItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReturnedQtyBySaleItems'
type MockReturnActivityReader_ReturnedQtyBySaleItems_Call struct {
	*mock.Call
}

// ReturnedQtyBySaleItems is a helper method to define mock.On call
//   - ctx context.Context
//   - saleItemIDs []uint
func (_e *MockReturnActivityReader_Expecter) ReturnedQtyBySaleItems(ctx interface{}, saleItemIDs interface{}) *MockReturnActivityReader_ReturnedQtyBySaleItems_Call {
	return &MockReturnActivityReader_ReturnedQtyBySaleItems_Call{Call: _e.mock.On("ReturnedQtyBySaleItems", ctx, saleItemIDs)}
}

func (_c *MockReturnActivityReader_ReturnedQtyBySaleItems_Call) Run(run func(ctx context.Context, saleItemIDs []uint)) *MockReturnActivityReader_ReturnedQtyBySaleItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockReturnActivityReader_ReturnedQtyBySaleItems_Call) Return(_a0 map[uint]int, _a1 error) *MockReturnActivityReader_ReturnedQtyBySaleItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReturnActivityReader_ReturnedQtyBySaleItems_Call) RunAndReturn(run func(context.Context, []uint) (map[uint]int, error)) *MockReturnActivityReader_ReturnedQtyBySaleItems_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReturnActivityReader creates a new instance of MockReturnActivityReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReturnActivityReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReturnActivityReader {
	mock := &MockReturnActivityReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
