// Code generated by mockery v2.53.3. DO NOT EDIT.

package sales

import (
	context "context"
	identity "shagan_pos/internal/identity"

	mock "github.com/stretchr/testify/mock"
)

// MockOrganizationLookup is an autogenerated mock type for the OrganizationLookup type
type MockOrganizationLookup struct {
	mock.Mock
}

type MockOrganizationLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizationLookup) EXPECT() *MockOrganizationLookup_Expecter {
	return &MockOrganizationLookup_Expecter{mock: &_m.Mock}
}

// GetOrganization provides a mock function with given fields: ctx, id
func (_m *MockOrganizationLookup) GetOrganization(ctx context.Context, id uint) (*identity.Organization, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganization")
	}

	var r0 *identity.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*identity.Organization, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *identity.Organization); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationLookup_GetOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganization'
type MockOrganizationLookup_GetOrganization_Call struct {
	*mock.Call
}

// GetOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockOrganizationLookup_Expecter) GetOrganization(ctx interface{}, id interface{}) *MockOrganizationLookup_GetOrganization_Call {
	return &MockOrganizationLookup_GetOrganization_Call{Call: _e.mock.On("GetOrganization", ctx, id)}
}

func (_c *MockOrganizationLookup_GetOrganization_Call) Run(run func(ctx context.Context, id uint)) *MockOrganizationLookup_GetOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockOrganizationLookup_GetOrganization_Call) Return(_a0 *identity.Organization, _a1 error) *MockOrganizationLookup_GetOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationLookup_GetOrganization_Call) RunAndReturn(run func(context.Context, uint) (*identity.Organization, error)) *MockOrganizationLookup_GetOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrganizationLookup creates a new instance of MockOrganizationLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizationLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizationLookup {
	mock := &MockOrganizationLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
