// Code generated by mockery v2.53.3. DO NOT EDIT.

package sales

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateHeldSale provides a mock function with given fields: ctx, in
func (_m *MockRepository) CreateHeldSale(ctx context.Context, in CreateHeldSaleRequest) (*HeldSale, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateHeldSale")
	}

	var r0 *HeldSale
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, CreateHeldSaleRequest) (*HeldSale, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, CreateHeldSaleRequest) *HeldSale); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*HeldSale)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, CreateHeldSaleRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateHeldSale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHeldSale'
type MockRepository_CreateHeldSale_Call struct {
	*mock.Call
}

// CreateHeldSale is a helper method to define mock.On call
//   - ctx context.Context
//   - in CreateHeldSaleRequest
func (_e *MockRepository_Expecter) CreateHeldSale(ctx interface{}, in interface{}) *MockRepository_CreateHeldSale_Call {
	return &MockRepository_CreateHeldSale_Call{Call: _e.mock.On("CreateHeldSale", ctx, in)}
}

func (_c *MockRepository_CreateHeldSale_Call) Run(run func(ctx context.Context, in CreateHeldSaleRequest)) *MockRepository_CreateHeldSale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(CreateHeldSaleRequest))
	})
	return _c
}

func (_c *MockRepository_CreateHeldSale_Call) Return(_a0 *HeldSale, _a1 error) *MockRepository_CreateHeldSale_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateHeldSale_Call) RunAndReturn(run func(context.Context, CreateHeldSaleRequest) (*HeldSale, error)) *MockRepository_CreateHeldSale_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePayments provides a mock function with given fields: db, payments
func (_m *MockRepository) CreatePayments(db *gorm.DB, payments []Payment) error {
	ret := _m.Called(db, payments)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, []Payment) error); ok {
		r0 = rf(db, payments)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreatePayments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayments'
type MockRepository_CreatePayments_Call struct {
	*mock.Call
}

// CreatePayments is a helper method to define mock.On call
//   - db *gorm.DB
//   - payments []Payment
func (_e *MockRepository_Expecter) CreatePayments(db interface{}, payments interface{}) *MockRepository_CreatePayments_Call {
	return &MockRepository_CreatePayments_Call{Call: _e.mock.On("CreatePayments", db, payments)}
}

func (_c *MockRepository_CreatePayments_Call) Run(run func(db *gorm.DB, payments []Payment)) *MockRepository_CreatePayments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].([]Payment))
	})
	return _c
}

func (_c *MockRepository_CreatePayments_Call) Return(_a0 error) *MockRepository_CreatePayments_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreatePayments_Call) RunAndReturn(run func(*gorm.DB, []Payment) error) *MockRepository_CreatePayments_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSale provides a mock function with given fields: db, sale
func (_m *MockRepository) CreateSale(db *gorm.DB, sale *Sale) error {
	ret := _m.Called(db, sale)

	if len(ret) == 0 {
		panic("no return value specified for CreateSale")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *Sale) error); ok {
		r0 = rf(db, sale)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateSale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSale'
type MockRepository_CreateSale_Call struct {
	*mock.Call
}

// CreateSale is a helper method to define mock.On call
//   - db *gorm.DB
//   - sale *Sale
func (_e *MockRepository_Expecter) CreateSale(db interface{}, sale interface{}) *MockRepository_CreateSale_Call {
	return &MockRepository_CreateSale_Call{Call: _e.mock.On("CreateSale", db, sale)}
}

func (_c *MockRepository_CreateSale_Call) Run(run func(db *gorm.DB, sale *Sale)) *MockRepository_CreateSale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*Sale))
	})
	return _c
}

func (_c *MockRepository_CreateSale_Call) Return(_a0 error) *MockRepository_CreateSale_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateSale_Call) RunAndReturn(run func(*gorm.DB, *Sale) error) *MockRepository_CreateSale_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSaleItems provides a mock function with given fields: db, items
func (_m *MockRepository) CreateSaleItems(db *gorm.DB, items []SaleItem) error {
	ret := _m.Called(db, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateSaleItems")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, []SaleItem) error); ok {
		r0 = rf(db, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateSaleItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSaleItems'
type MockRepository_CreateSaleItems_Call struct {
	*mock.Call
}

// CreateSaleItems is a helper method to define mock.On call
//   - db *gorm.DB
//   - items []SaleItem
func (_e *MockRepository_Expecter) CreateSaleItems(db interface{}, items interface{}) *MockRepository_CreateSaleItems_Call {
	return &MockRepository_CreateSaleItems_Call{Call: _e.mock.On("CreateSaleItems", db, items)}
}

func (_c *MockRepository_CreateSaleItems_Call) Run(run func(db *gorm.DB, items []SaleItem)) *MockRepository_CreateSaleItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].([]SaleItem))
	})
	return _c
}

func (_c *MockRepository_CreateSaleItems_Call) Return(_a0 error) *MockRepository_CreateSaleItems_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateSaleItems_Call) RunAndReturn(run func(*gorm.DB, []SaleItem) error) *MockRepository_CreateSaleItems_Call {
	_c.Call.Return(run)
	return _c
}

// GetSale provides a mock function with given fields: ctx, orgID, id
func (_m *MockRepository) GetSale(ctx context.Context, orgID uint, id uuid.UUID) (*Sale, error) {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSale")
	}

	var r0 *Sale
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uuid.UUID) (*Sale, error)); ok {
		return rf(ctx, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uuid.UUID) *Sale); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Sale)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetSale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSale'
type MockRepository_GetSale_Call struct {
	*mock.Call
}

// GetSale is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetSale(ctx interface{}, orgID interface{}, id interface{}) *MockRepository_GetSale_Call {
	return &MockRepository_GetSale_Call{Call: _e.mock.On("GetSale", ctx, orgID, id)}
}

func (_c *MockRepository_GetSale_Call) Run(run func(ctx context.Context, orgID uint, id uuid.UUID)) *MockRepository_GetSale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetSale_Call) Return(_a0 *Sale, _a1 error) *MockRepository_GetSale_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetSale_Call) RunAndReturn(run func(context.Context, uint, uuid.UUID) (*Sale, error)) *MockRepository_GetSale_Call {
	_c.Call.Return(run)
	return _c
}

// GetSaleWithLock provides a mock function with given fields: db, orgID, id
func (_m *MockRepository) GetSaleWithLock(db *gorm.DB, orgID uint, id uuid.UUID) (*Sale, error) {
	ret := _m.Called(db, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSaleWithLock")
	}

	var r0 *Sale
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, uuid.UUID) (*Sale, error)); ok {
		return rf(db, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, uuid.UUID) *Sale); ok {
		r0 = rf(db, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Sale)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, uint, uuid.UUID) error); ok {
		r1 = rf(db, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetSaleWithLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSaleWithLock'
type MockRepository_GetSaleWithLock_Call struct {
	*mock.Call
}

// GetSaleWithLock is a helper method to define mock.On call
//   - db *gorm.DB
//   - orgID uint
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetSaleWithLock(db interface{}, orgID interface{}, id interface{}) *MockRepository_GetSaleWithLock_Call {
	return &MockRepository_GetSaleWithLock_Call{Call: _e.mock.On("GetSaleWithLock", db, orgID, id)}
}

func (_c *MockRepository_GetSaleWithLock_Call) Run(run func(db *gorm.DB, orgID uint, id uuid.UUID)) *MockRepository_GetSaleWithLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetSaleWithLock_Call) Return(_a0 *Sale, _a1 error) *MockRepository_GetSaleWithLock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetSaleWithLock_Call) RunAndReturn(run func(*gorm.DB, uint, uuid.UUID) (*Sale, error)) *MockRepository_GetSaleWithLock_Call {
	_c.Call.Return(run)
	return _c
}

// ListHeldSales provides a mock function with given fields: ctx, branchID
func (_m *MockRepository) ListHeldSales(ctx context.Context, branchID uint) ([]HeldSale, error) {
	ret := _m.Called(ctx, branchID)

	if len(ret) == 0 {
		panic("no return value specified for ListHeldSales")
	}

	var r0 []HeldSale
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]HeldSale, error)); ok {
		return rf(ctx, branchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []HeldSale); ok {
		r0 = rf(ctx, branchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]HeldSale)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, branchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListHeldSales_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHeldSales'
type MockRepository_ListHeldSales_Call struct {
	*mock.Call
}

// ListHeldSales is a helper method to define mock.On call
//   - ctx context.Context
//   - branchID uint
func (_e *MockRepository_Expecter) ListHeldSales(ctx interface{}, branchID interface{}) *MockRepository_ListHeldSales_Call {
	return &MockRepository_ListHeldSales_Call{Call: _e.mock.On("ListHeldSales", ctx, branchID)}
}

func (_c *MockRepository_ListHeldSales_Call) Run(run func(ctx context.Context, branchID uint)) *MockRepository_ListHeldSales_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_ListHeldSales_Call) Return(_a0 []HeldSale, _a1 error) *MockRepository_ListHeldSales_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListHeldSales_Call) RunAndReturn(run func(context.Context, uint) ([]HeldSale, error)) *MockRepository_ListHeldSales_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaymentMethods provides a mock function with given fields: ctx, saleIDs
func (_m *MockRepository) ListPaymentMethods(ctx context.Context, saleIDs []uuid.UUID) (map[uuid.UUID][]PaymentMethod, error) {
	ret := _m.Called(ctx, saleIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListPaymentMethods")
	}

	var r0 map[uuid.UUID][]PaymentMethod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID][]PaymentMethod, error)); ok {
		return rf(ctx, saleIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID][]PaymentMethod); ok {
		r0 = rf(ctx, saleIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]PaymentMethod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, saleIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListPaymentMethods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPaymentMethods'
type MockRepository_ListPaymentMethods_Call struct {
	*mock.Call
}

// ListPaymentMethods is a helper method to define mock.On call
//   - ctx context.Context
//   - saleIDs []uuid.UUID
func (_e *MockRepository_Expecter) ListPaymentMethods(ctx interface{}, saleIDs interface{}) *MockRepository_ListPaymentMethods_Call {
	return &MockRepository_ListPaymentMethods_Call{Call: _e.mock.On("ListPaymentMethods", ctx, saleIDs)}
}

func (_c *MockRepository_ListPaymentMethods_Call) Run(run func(ctx context.Context, saleIDs []uuid.UUID)) *MockRepository_ListPaymentMethods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ListPaymentMethods_Call) Return(_a0 map[uuid.UUID][]PaymentMethod, _a1 error) *MockRepository_ListPaymentMethods_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListPaymentMethods_Call) RunAndReturn(run func(context.Context, []uuid.UUID) (map[uuid.UUID][]PaymentMethod, error)) *MockRepository_ListPaymentMethods_Call {
	_c.Call.Return(run)
	return _c
}

// ListPayments provides a mock function with given fields: ctx, saleID
func (_m *MockRepository) ListPayments(ctx context.Context, saleID uuid.UUID) ([]Payment, error) {
	ret := _m.Called(ctx, saleID)

	if len(ret) == 0 {
		panic("no return value specified for ListPayments")
	}

	var r0 []Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]Payment, error)); ok {
		return rf(ctx, saleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []Payment); ok {
		r0 = rf(ctx, saleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, saleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListPayments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPayments'
type MockRepository_ListPayments_Call struct {
	*mock.Call
}

// ListPayments is a helper method to define mock.On call
//   - ctx context.Context
//   - saleID uuid.UUID
func (_e *MockRepository_Expecter) ListPayments(ctx interface{}, saleID interface{}) *MockRepository_ListPayments_Call {
	return &MockRepository_ListPayments_Call{Call: _e.mock.On("ListPayments", ctx, saleID)}
}

func (_c *MockRepository_ListPayments_Call) Run(run func(ctx context.Context, saleID uuid.UUID)) *MockRepository_ListPayments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ListPayments_Call) Return(_a0 []Payment, _a1 error) *MockRepository_ListPayments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListPayments_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]Payment, error)) *MockRepository_ListPayments_Call {
	_c.Call.Return(run)
	return _c
}

// ListSaleItems provides a mock function with given fields: ctx, saleID
func (_m *MockRepository) ListSaleItems(ctx context.Context, saleID uuid.UUID) ([]SaleItem, error) {
	ret := _m.Called(ctx, saleID)

	if len(ret) == 0 {
		panic("no return value specified for ListSaleItems")
	}

	var r0 []SaleItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]SaleItem, error)); ok {
		return rf(ctx, saleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []SaleItem); ok {
		r0 = rf(ctx, saleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SaleItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, saleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListSaleItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSaleItems'
type MockRepository_ListSaleItems_Call struct {
	*mock.Call
}

// ListSaleItems is a helper method to define mock.On call
//   - ctx context.Context
//   - saleID uuid.UUID
func (_e *MockRepository_Expecter) ListSaleItems(ctx interface{}, saleID interface{}) *MockRepository_ListSaleItems_Call {
	return &MockRepository_ListSaleItems_Call{Call: _e.mock.On("ListSaleItems", ctx, saleID)}
}

func (_c *MockRepository_ListSaleItems_Call) Run(run func(ctx context.Context, saleID uuid.UUID)) *MockRepository_ListSaleItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ListSaleItems_Call) Return(_a0 []SaleItem, _a1 error) *MockRepository_ListSaleItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListSaleItems_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]SaleItem, error)) *MockRepository_ListSaleItems_Call {
	_c.Call.Return(run)
	return _c
}

// ListSaleItemsTx provides a mock function with given fields: db, saleID
func (_m *MockRepository) ListSaleItemsTx(db *gorm.DB, saleID uuid.UUID) ([]SaleItem, error) {
	ret := _m.Called(db, saleID)

	if len(ret) == 0 {
		panic("no return value specified for ListSaleItemsTx")
	}

	var r0 []SaleItem
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uuid.UUID) ([]SaleItem, error)); ok {
		return rf(db, saleID)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, uuid.UUID) []SaleItem); ok {
		r0 = rf(db, saleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SaleItem)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, uuid.UUID) error); ok {
		r1 = rf(db, saleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListSaleItemsTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSaleItemsTx'
type MockRepository_ListSaleItemsTx_Call struct {
	*mock.Call
}

// ListSaleItemsTx is a helper method to define mock.On call
//   - db *gorm.DB
//   - saleID uuid.UUID
func (_e *MockRepository_Expecter) ListSaleItemsTx(db interface{}, saleID interface{}) *MockRepository_ListSaleItemsTx_Call {
	return &MockRepository_ListSaleItemsTx_Call{Call: _e.mock.On("ListSaleItemsTx", db, saleID)}
}

func (_c *MockRepository_ListSaleItemsTx_Call) Run(run func(db *gorm.DB, saleID uuid.UUID)) *MockRepository_ListSaleItemsTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ListSaleItemsTx_Call) Return(_a0 []SaleItem, _a1 error) *MockRepository_ListSaleItemsTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListSaleItemsTx_Call) RunAndReturn(run func(*gorm.DB, uuid.UUID) ([]SaleItem, error)) *MockRepository_ListSaleItemsTx_Call {
	_c.Call.Return(run)
	return _c
}

// ListSales provides a mock function with given fields: ctx, orgID, f
func (_m *MockRepository) ListSales(ctx context.Context, orgID uint, f SaleFilter) ([]Sale, int64, error) {
	ret := _m.Called(ctx, orgID, f)

	if len(ret) == 0 {
		panic("no return value specified for ListSales")
	}

	var r0 []Sale
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, SaleFilter) ([]Sale, int64, error)); ok {
		return rf(ctx, orgID, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, SaleFilter) []Sale); ok {
		r0 = rf(ctx, orgID, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Sale)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, SaleFilter) int64); ok {
		r1 = rf(ctx, orgID, f)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, SaleFilter) error); ok {
		r2 = rf(ctx, orgID, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_ListSales_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSales'
type MockRepository_ListSales_Call struct {
	*mock.Call
}

// ListSales is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - f SaleFilter
func (_e *MockRepository_Expecter) ListSales(ctx interface{}, orgID interface{}, f interface{}) *MockRepository_ListSales_Call {
	return &MockRepository_ListSales_Call{Call: _e.mock.On("ListSales", ctx, orgID, f)}
}

func (_c *MockRepository_ListSales_Call) Run(run func(ctx context.Context, orgID uint, f SaleFilter)) *MockRepository_ListSales_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(SaleFilter))
	})
	return _c
}

func (_c *MockRepository_ListSales_Call) Return(_a0 []Sale, _a1 int64, _a2 error) *MockRepository_ListSales_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_ListSales_Call) RunAndReturn(run func(context.Context, uint, SaleFilter) ([]Sale, int64, error)) *MockRepository_ListSales_Call {
	_c.Call.Return(run)
	return _c
}

// RequireOpenShift provides a mock function with given fields: db, orgID, branchID, shiftID
func (_m *MockRepository) RequireOpenShift(db *gorm.DB, orgID uint, branchID uint, shiftID uint) error {
	ret := _m.Called(db, orgID, branchID, shiftID)

	if len(ret) == 0 {
		panic("no return value specified for RequireOpenShift")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, uint, uint) error); ok {
		r0 = rf(db, orgID, branchID, shiftID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_RequireOpenShift_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireOpenShift'
type MockRepository_RequireOpenShift_Call struct {
	*mock.Call
}

// RequireOpenShift is a helper method to define mock.On call
//   - db *gorm.DB
//   - orgID uint
//   - branchID uint
//   - shiftID uint
func (_e *MockRepository_Expecter) RequireOpenShift(db interface{}, orgID interface{}, branchID interface{}, shiftID interface{}) *MockRepository_RequireOpenShift_Call {
	return &MockRepository_RequireOpenShift_Call{Call: _e.mock.On("RequireOpenShift", db, orgID, branchID, shiftID)}
}

func (_c *MockRepository_RequireOpenShift_Call) Run(run func(db *gorm.DB, orgID uint, branchID uint, shiftID uint)) *MockRepository_RequireOpenShift_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint), args[2].(uint), args[3].(uint))
	})
	return _c
}

func (_c *MockRepository_RequireOpenShift_Call) Return(_a0 error) *MockRepository_RequireOpenShift_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_RequireOpenShift_Call) RunAndReturn(run func(*gorm.DB, uint, uint, uint) error) *MockRepository_RequireOpenShift_Call {
	_c.Call.Return(run)
	return _c
}

// ResumeHeldSale provides a mock function with given fields: ctx, branchID, id
func (_m *MockRepository) ResumeHeldSale(ctx context.Context, branchID uint, id uint) (*HeldSale, error) {
	ret := _m.Called(ctx, branchID, id)

	if len(ret) == 0 {
		panic("no return value specified for ResumeHeldSale")
	}

	var r0 *HeldSale
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*HeldSale, error)); ok {
		return rf(ctx, branchID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *HeldSale); ok {
		r0 = rf(ctx, branchID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*HeldSale)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, branchID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ResumeHeldSale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResumeHeldSale'
type MockRepository_ResumeHeldSale_Call struct {
	*mock.Call
}

// ResumeHeldSale is a helper method to define mock.On call
//   - ctx context.Context
//   - branchID uint
//   - id uint
func (_e *MockRepository_Expecter) ResumeHeldSale(ctx interface{}, branchID interface{}, id interface{}) *MockRepository_ResumeHeldSale_Call {
	return &MockRepository_ResumeHeldSale_Call{Call: _e.mock.On("ResumeHeldSale", ctx, branchID, id)}
}

func (_c *MockRepository_ResumeHeldSale_Call) Run(run func(ctx context.Context, branchID uint, id uint)) *MockRepository_ResumeHeldSale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockRepository_ResumeHeldSale_Call) Return(_a0 *HeldSale, _a1 error) *MockRepository_ResumeHeldSale_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ResumeHeldSale_Call) RunAndReturn(run func(context.Context, uint, uint) (*HeldSale, error)) *MockRepository_ResumeHeldSale_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSaleStatus provides a mock function with given fields: db, id, status
func (_m *MockRepository) UpdateSaleStatus(db *gorm.DB, id uuid.UUID, status SaleStatus) error {
	ret := _m.Called(db, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSaleStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uuid.UUID, SaleStatus) error); ok {
		r0 = rf(db, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateSaleStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSaleStatus'
type MockRepository_UpdateSaleStatus_Call struct {
	*mock.Call
}

// UpdateSaleStatus is a helper method to define mock.On call
//   - db *gorm.DB
//   - id uuid.UUID
//   - status SaleStatus
func (_e *MockRepository_Expecter) UpdateSaleStatus(db interface{}, id interface{}, status interface{}) *MockRepository_UpdateSaleStatus_Call {
	return &MockRepository_UpdateSaleStatus_Call{Call: _e.mock.On("UpdateSaleStatus", db, id, status)}
}

func (_c *MockRepository_UpdateSaleStatus_Call) Run(run func(db *gorm.DB, id uuid.UUID, status SaleStatus)) *MockRepository_UpdateSaleStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uuid.UUID), args[2].(SaleStatus))
	})
	return _c
}

func (_c *MockRepository_UpdateSaleStatus_Call) Return(_a0 error) *MockRepository_UpdateSaleStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateSaleStatus_Call) RunAndReturn(run func(*gorm.DB, uuid.UUID, SaleStatus) error) *MockRepository_UpdateSaleStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
