// Code generated by mockery v2.53.3. DO NOT EDIT.

package identity

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function with given fields: ctx, in
func (_m *MockRepository) CreateAccount(ctx context.Context, in CreateAccountInput) (*CreateAccountResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 *CreateAccountResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, CreateAccountInput) (*CreateAccountResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, CreateAccountInput) *CreateAccountResult); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CreateAccountResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, CreateAccountInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockRepository_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - in CreateAccountInput
func (_e *MockRepository_Expecter) CreateAccount(ctx interface{}, in interface{}) *MockRepository_CreateAccount_Call {
	return &MockRepository_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, in)}
}

func (_c *MockRepository_CreateAccount_Call) Run(run func(ctx context.Context, in CreateAccountInput)) *MockRepository_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(CreateAccountInput))
	})
	return _c
}

func (_c *MockRepository_CreateAccount_Call) Return(_a0 *CreateAccountResult, _a1 error) *MockRepository_CreateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateAccount_Call) RunAndReturn(run func(context.Context, CreateAccountInput) (*CreateAccountResult, error)) *MockRepository_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBranch provides a mock function with given fields: ctx, in
func (_m *MockRepository) CreateBranch(ctx context.Context, in CreateBranchRequest) (*Branch, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateBranch")
	}

	var r0 *Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, CreateBranchRequest) (*Branch, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, CreateBranchRequest) *Branch); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, CreateBranchRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBranch'
type MockRepository_CreateBranch_Call struct {
	*mock.Call
}

// CreateBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - in CreateBranchRequest
func (_e *MockRepository_Expecter) CreateBranch(ctx interface{}, in interface{}) *MockRepository_CreateBranch_Call {
	return &MockRepository_CreateBranch_Call{Call: _e.mock.On("CreateBranch", ctx, in)}
}

func (_c *MockRepository_CreateBranch_Call) Run(run func(ctx context.Context, in CreateBranchRequest)) *MockRepository_CreateBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(CreateBranchRequest))
	})
	return _c
}

func (_c *MockRepository_CreateBranch_Call) Return(_a0 *Branch, _a1 error) *MockRepository_CreateBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateBranch_Call) RunAndReturn(run func(context.Context, CreateBranchRequest) (*Branch, error)) *MockRepository_CreateBranch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function with given fields: ctx, userID, refreshHash, expiresAt
func (_m *MockRepository) CreateSession(ctx context.Context, userID uint, refreshHash string, expiresAt time.Time) (*Session, error) {
	ret := _m.Called(ctx, userID, refreshHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, time.Time) (*Session, error)); ok {
		return rf(ctx, userID, refreshHash, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, time.Time) *Session); ok {
		r0 = rf(ctx, userID, refreshHash, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string, time.Time) error); ok {
		r1 = rf(ctx, userID, refreshHash, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - refreshHash string
//   - expiresAt time.Time
func (_e *MockRepository_Expecter) CreateSession(ctx interface{}, userID interface{}, refreshHash interface{}, expiresAt interface{}) *MockRepository_CreateSession_Call {
	return &MockRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID, refreshHash, expiresAt)}
}

func (_c *MockRepository_CreateSession_Call) Run(run func(ctx context.Context, userID uint, refreshHash string, expiresAt time.Time)) *MockRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepository_CreateSession_Call) Return(_a0 *Session, _a1 error) *MockRepository_CreateSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateSession_Call) RunAndReturn(run func(context.Context, uint, string, time.Time) (*Session, error)) *MockRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStaff provides a mock function with given fields: ctx, in
func (_m *MockRepository) CreateStaff(ctx context.Context, in CreateStaffRequest) (*Staff, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateStaff")
	}

	var r0 *Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, CreateStaffRequest) (*Staff, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, CreateStaffRequest) *Staff); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, CreateStaffRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStaff'
type MockRepository_CreateStaff_Call struct {
	*mock.Call
}

// CreateStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - in CreateStaffRequest
func (_e *MockRepository_Expecter) CreateStaff(ctx interface{}, in interface{}) *MockRepository_CreateStaff_Call {
	return &MockRepository_CreateStaff_Call{Call: _e.mock.On("CreateStaff", ctx, in)}
}

func (_c *MockRepository_CreateStaff_Call) Run(run func(ctx context.Context, in CreateStaffRequest)) *MockRepository_CreateStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(CreateStaffRequest))
	})
	return _c
}

func (_c *MockRepository_CreateStaff_Call) Return(_a0 *Staff, _a1 error) *MockRepository_CreateStaff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateStaff_Call) RunAndReturn(run func(context.Context, CreateStaffRequest) (*Staff, error)) *MockRepository_CreateStaff_Call {
	_c.Call.Return(run)
	return _c
}

// GetBranch provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetBranch(ctx context.Context, id uint) (*Branch, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBranch")
	}

	var r0 *Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*Branch, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *Branch); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBranch'
type MockRepository_GetBranch_Call struct {
	*mock.Call
}

// GetBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRepository_Expecter) GetBranch(ctx interface{}, id interface{}) *MockRepository_GetBranch_Call {
	return &MockRepository_GetBranch_Call{Call: _e.mock.On("GetBranch", ctx, id)}
}

func (_c *MockRepository_GetBranch_Call) Run(run func(ctx context.Context, id uint)) *MockRepository_GetBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_GetBranch_Call) Return(_a0 *Branch, _a1 error) *MockRepository_GetBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetBranch_Call) RunAndReturn(run func(context.Context, uint) (*Branch, error)) *MockRepository_GetBranch_Call {
	_c.Call.Return(run)
	return _c
}

// GetMe provides a mock function with given fields: ctx
func (_m *MockRepository) GetMe(ctx context.Context) (*User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type MockRepository_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetMe(ctx interface{}) *MockRepository_GetMe_Call {
	return &MockRepository_GetMe_Call{Call: _e.mock.On("GetMe", ctx)}
}

func (_c *MockRepository_GetMe_Call) Run(run func(ctx context.Context)) *MockRepository_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetMe_Call) Return(_a0 *User, _a1 error) *MockRepository_GetMe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetMe_Call) RunAndReturn(run func(context.Context) (*User, error)) *MockRepository_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByRefreshHash provides a mock function with given fields: ctx, refreshHash
func (_m *MockRepository) GetSessionByRefreshHash(ctx context.Context, refreshHash string) (*Session, error) {
	ret := _m.Called(ctx, refreshHash)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByRefreshHash")
	}

	var r0 *Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Session, error)); ok {
		return rf(ctx, refreshHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Session); ok {
		r0 = rf(ctx, refreshHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetSessionByRefreshHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByRefreshHash'
type MockRepository_GetSessionByRefreshHash_Call struct {
	*mock.Call
}

// GetSessionByRefreshHash is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshHash string
func (_e *MockRepository_Expecter) GetSessionByRefreshHash(ctx interface{}, refreshHash interface{}) *MockRepository_GetSessionByRefreshHash_Call {
	return &MockRepository_GetSessionByRefreshHash_Call{Call: _e.mock.On("GetSessionByRefreshHash", ctx, refreshHash)}
}

func (_c *MockRepository_GetSessionByRefreshHash_Call) Run(run func(ctx context.Context, refreshHash string)) *MockRepository_GetSessionByRefreshHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetSessionByRefreshHash_Call) Return(_a0 *Session, _a1 error) *MockRepository_GetSessionByRefreshHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetSessionByRefreshHash_Call) RunAndReturn(run func(context.Context, string) (*Session, error)) *MockRepository_GetSessionByRefreshHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetStaff provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetStaff(ctx context.Context, id uint) (*Staff, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetStaff")
	}

	var r0 *Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*Staff, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *Staff); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStaff'
type MockRepository_GetStaff_Call struct {
	*mock.Call
}

// GetStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRepository_Expecter) GetStaff(ctx interface{}, id interface{}) *MockRepository_GetStaff_Call {
	return &MockRepository_GetStaff_Call{Call: _e.mock.On("GetStaff", ctx, id)}
}

func (_c *MockRepository_GetStaff_Call) Run(run func(ctx context.Context, id uint)) *MockRepository_GetStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_GetStaff_Call) Return(_a0 *Staff, _a1 error) *MockRepository_GetStaff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetStaff_Call) RunAndReturn(run func(context.Context, uint) (*Staff, error)) *MockRepository_GetStaff_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockRepository) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRepository_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockRepository_GetUserByEmail_Call {
	return &MockRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockRepository_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetUserByEmail_Call) Return(_a0 *User, _a1 error) *MockRepository_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*User, error)) *MockRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetUserByID(ctx context.Context, id uint) (*User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRepository_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockRepository_GetUserByID_Call {
	return &MockRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockRepository_GetUserByID_Call) Run(run func(ctx context.Context, id uint)) *MockRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_GetUserByID_Call) Return(_a0 *User, _a1 error) *MockRepository_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserByID_Call) RunAndReturn(run func(context.Context, uint) (*User, error)) *MockRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListBranchStaff provides a mock function with given fields: ctx, id
func (_m *MockRepository) ListBranchStaff(ctx context.Context, id uint) ([]Staff, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ListBranchStaff")
	}

	var r0 []Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]Staff, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []Staff); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListBranchStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBranchStaff'
type MockRepository_ListBranchStaff_Call struct {
	*mock.Call
}

// ListBranchStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRepository_Expecter) ListBranchStaff(ctx interface{}, id interface{}) *MockRepository_ListBranchStaff_Call {
	return &MockRepository_ListBranchStaff_Call{Call: _e.mock.On("ListBranchStaff", ctx, id)}
}

func (_c *MockRepository_ListBranchStaff_Call) Run(run func(ctx context.Context, id uint)) *MockRepository_ListBranchStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_ListBranchStaff_Call) Return(_a0 []Staff, _a1 error) *MockRepository_ListBranchStaff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListBranchStaff_Call) RunAndReturn(run func(context.Context, uint) ([]Staff, error)) *MockRepository_ListBranchStaff_Call {
	_c.Call.Return(run)
	return _c
}

// ListBranches provides a mock function with given fields: ctx
func (_m *MockRepository) ListBranches(ctx context.Context) ([]Branch, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListBranches")
	}

	var r0 []Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]Branch, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []Branch); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListBranches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBranches'
type MockRepository_ListBranches_Call struct {
	*mock.Call
}

// ListBranches is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListBranches(ctx interface{}) *MockRepository_ListBranches_Call {
	return &MockRepository_ListBranches_Call{Call: _e.mock.On("ListBranches", ctx)}
}

func (_c *MockRepository_ListBranches_Call) Run(run func(ctx context.Context)) *MockRepository_ListBranches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListBranches_Call) Return(_a0 []Branch, _a1 error) *MockRepository_ListBranches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListBranches_Call) RunAndReturn(run func(context.Context) ([]Branch, error)) *MockRepository_ListBranches_Call {
	_c.Call.Return(run)
	return _c
}

// ListDevices provides a mock function with given fields: ctx
func (_m *MockRepository) ListDevices(ctx context.Context) ([]Device, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListDevices")
	}

	var r0 []Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]Device, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []Device); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDevices'
type MockRepository_ListDevices_Call struct {
	*mock.Call
}

// ListDevices is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListDevices(ctx interface{}) *MockRepository_ListDevices_Call {
	return &MockRepository_ListDevices_Call{Call: _e.mock.On("ListDevices", ctx)}
}

func (_c *MockRepository_ListDevices_Call) Run(run func(ctx context.Context)) *MockRepository_ListDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListDevices_Call) Return(_a0 []Device, _a1 error) *MockRepository_ListDevices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListDevices_Call) RunAndReturn(run func(context.Context) ([]Device, error)) *MockRepository_ListDevices_Call {
	_c.Call.Return(run)
	return _c
}

// ListPermissions provides a mock function with given fields: ctx
func (_m *MockRepository) ListPermissions(ctx context.Context) ([]Permission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPermissions")
	}

	var r0 []Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]Permission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPermissions'
type MockRepository_ListPermissions_Call struct {
	*mock.Call
}

// ListPermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListPermissions(ctx interface{}) *MockRepository_ListPermissions_Call {
	return &MockRepository_ListPermissions_Call{Call: _e.mock.On("ListPermissions", ctx)}
}

func (_c *MockRepository_ListPermissions_Call) Run(run func(ctx context.Context)) *MockRepository_ListPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListPermissions_Call) Return(_a0 []Permission, _a1 error) *MockRepository_ListPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListPermissions_Call) RunAndReturn(run func(context.Context) ([]Permission, error)) *MockRepository_ListPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// ListRolePermissions provides a mock function with given fields: ctx, id
func (_m *MockRepository) ListRolePermissions(ctx context.Context, id uint) ([]Permission, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ListRolePermissions")
	}

	var r0 []Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]Permission, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []Permission); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListRolePermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRolePermissions'
type MockRepository_ListRolePermissions_Call struct {
	*mock.Call
}

// ListRolePermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRepository_Expecter) ListRolePermissions(ctx interface{}, id interface{}) *MockRepository_ListRolePermissions_Call {
	return &MockRepository_ListRolePermissions_Call{Call: _e.mock.On("ListRolePermissions", ctx, id)}
}

func (_c *MockRepository_ListRolePermissions_Call) Run(run func(ctx context.Context, id uint)) *MockRepository_ListRolePermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_ListRolePermissions_Call) Return(_a0 []Permission, _a1 error) *MockRepository_ListRolePermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListRolePermissions_Call) RunAndReturn(run func(context.Context, uint) ([]Permission, error)) *MockRepository_ListRolePermissions_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoles provides a mock function with given fields: ctx
func (_m *MockRepository) ListRoles(ctx context.Context) ([]Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRoles")
	}

	var r0 []Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoles'
type MockRepository_ListRoles_Call struct {
	*mock.Call
}

// ListRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListRoles(ctx interface{}) *MockRepository_ListRoles_Call {
	return &MockRepository_ListRoles_Call{Call: _e.mock.On("ListRoles", ctx)}
}

func (_c *MockRepository_ListRoles_Call) Run(run func(ctx context.Context)) *MockRepository_ListRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListRoles_Call) Return(_a0 []Role, _a1 error) *MockRepository_ListRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListRoles_Call) RunAndReturn(run func(context.Context) ([]Role, error)) *MockRepository_ListRoles_Call {
	_c.Call.Return(run)
	return _c
}

// ListStaff provides a mock function with given fields: ctx
func (_m *MockRepository) ListStaff(ctx context.Context) ([]Staff, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListStaff")
	}

	var r0 []Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]Staff, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []Staff); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStaff'
type MockRepository_ListStaff_Call struct {
	*mock.Call
}

// ListStaff is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListStaff(ctx interface{}) *MockRepository_ListStaff_Call {
	return &MockRepository_ListStaff_Call{Call: _e.mock.On("ListStaff", ctx)}
}

func (_c *MockRepository_ListStaff_Call) Run(run func(ctx context.Context)) *MockRepository_ListStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListStaff_Call) Return(_a0 []Staff, _a1 error) *MockRepository_ListStaff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListStaff_Call) RunAndReturn(run func(context.Context) ([]Staff, error)) *MockRepository_ListStaff_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterDevice provides a mock function with given fields: ctx, in
func (_m *MockRepository) RegisterDevice(ctx context.Context, in RegisterDeviceRequest) (*Device, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for RegisterDevice")
	}

	var r0 *Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, RegisterDeviceRequest) (*Device, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, RegisterDeviceRequest) *Device); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, RegisterDeviceRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_RegisterDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterDevice'
type MockRepository_RegisterDevice_Call struct {
	*mock.Call
}

// RegisterDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - in RegisterDeviceRequest
func (_e *MockRepository_Expecter) RegisterDevice(ctx interface{}, in interface{}) *MockRepository_RegisterDevice_Call {
	return &MockRepository_RegisterDevice_Call{Call: _e.mock.On("RegisterDevice", ctx, in)}
}

func (_c *MockRepository_RegisterDevice_Call) Run(run func(ctx context.Context, in RegisterDeviceRequest)) *MockRepository_RegisterDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(RegisterDeviceRequest))
	})
	return _c
}

func (_c *MockRepository_RegisterDevice_Call) Return(_a0 *Device, _a1 error) *MockRepository_RegisterDevice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_RegisterDevice_Call) RunAndReturn(run func(context.Context, RegisterDeviceRequest) (*Device, error)) *MockRepository_RegisterDevice_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function with given fields: ctx, sessionID
func (_m *MockRepository) RevokeSession(ctx context.Context, sessionID uint) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockRepository_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uint
func (_e *MockRepository_Expecter) RevokeSession(ctx interface{}, sessionID interface{}) *MockRepository_RevokeSession_Call {
	return &MockRepository_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, sessionID)}
}

func (_c *MockRepository_RevokeSession_Call) Run(run func(ctx context.Context, sessionID uint)) *MockRepository_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_RevokeSession_Call) Return(_a0 error) *MockRepository_RevokeSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_RevokeSession_Call) RunAndReturn(run func(context.Context, uint) error) *MockRepository_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBranch provides a mock function with given fields: ctx, id, in
func (_m *MockRepository) UpdateBranch(ctx context.Context, id uint, in UpdateBranchRequest) (*Branch, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBranch")
	}

	var r0 *Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, UpdateBranchRequest) (*Branch, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, UpdateBranchRequest) *Branch); ok {
		r0 = rf(ctx, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, UpdateBranchRequest) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBranch'
type MockRepository_UpdateBranch_Call struct {
	*mock.Call
}

// UpdateBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - in UpdateBranchRequest
func (_e *MockRepository_Expecter) UpdateBranch(ctx interface{}, id interface{}, in interface{}) *MockRepository_UpdateBranch_Call {
	return &MockRepository_UpdateBranch_Call{Call: _e.mock.On("UpdateBranch", ctx, id, in)}
}

func (_c *MockRepository_UpdateBranch_Call) Run(run func(ctx context.Context, id uint, in UpdateBranchRequest)) *MockRepository_UpdateBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(UpdateBranchRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateBranch_Call) Return(_a0 *Branch, _a1 error) *MockRepository_UpdateBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateBranch_Call) RunAndReturn(run func(context.Context, uint, UpdateBranchRequest) (*Branch, error)) *MockRepository_UpdateBranch_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDevice provides a mock function with given fields: ctx, id, in
func (_m *MockRepository) UpdateDevice(ctx context.Context, id uint, in UpdateDeviceRequest) (*Device, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDevice")
	}

	var r0 *Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, UpdateDeviceRequest) (*Device, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, UpdateDeviceRequest) *Device); ok {
		r0 = rf(ctx, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, UpdateDeviceRequest) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDevice'
type MockRepository_UpdateDevice_Call struct {
	*mock.Call
}

// UpdateDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - in UpdateDeviceRequest
func (_e *MockRepository_Expecter) UpdateDevice(ctx interface{}, id interface{}, in interface{}) *MockRepository_UpdateDevice_Call {
	return &MockRepository_UpdateDevice_Call{Call: _e.mock.On("UpdateDevice", ctx, id, in)}
}

func (_c *MockRepository_UpdateDevice_Call) Run(run func(ctx context.Context, id uint, in UpdateDeviceRequest)) *MockRepository_UpdateDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(UpdateDeviceRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateDevice_Call) Return(_a0 *Device, _a1 error) *MockRepository_UpdateDevice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateDevice_Call) RunAndReturn(run func(context.Context, uint, UpdateDeviceRequest) (*Device, error)) *MockRepository_UpdateDevice_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMe provides a mock function with given fields: ctx, in
func (_m *MockRepository) UpdateMe(ctx context.Context, in UpdateMeRequest) (*User, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMe")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, UpdateMeRequest) (*User, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, UpdateMeRequest) *User); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, UpdateMeRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMe'
type MockRepository_UpdateMe_Call struct {
	*mock.Call
}

// UpdateMe is a helper method to define mock.On call
//   - ctx context.Context
//   - in UpdateMeRequest
func (_e *MockRepository_Expecter) UpdateMe(ctx interface{}, in interface{}) *MockRepository_UpdateMe_Call {
	return &MockRepository_UpdateMe_Call{Call: _e.mock.On("UpdateMe", ctx, in)}
}

func (_c *MockRepository_UpdateMe_Call) Run(run func(ctx context.Context, in UpdateMeRequest)) *MockRepository_UpdateMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(UpdateMeRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateMe_Call) Return(_a0 *User, _a1 error) *MockRepository_UpdateMe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateMe_Call) RunAndReturn(run func(context.Context, UpdateMeRequest) (*User, error)) *MockRepository_UpdateMe_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStaff provides a mock function with given fields: ctx, id, in
func (_m *MockRepository) UpdateStaff(ctx context.Context, id uint, in UpdateStaffRequest) (*Staff, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStaff")
	}

	var r0 *Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, UpdateStaffRequest) (*Staff, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, UpdateStaffRequest) *Staff); ok {
		r0 = rf(ctx, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, UpdateStaffRequest) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStaff'
type MockRepository_UpdateStaff_Call struct {
	*mock.Call
}

// UpdateStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - in UpdateStaffRequest
func (_e *MockRepository_Expecter) UpdateStaff(ctx interface{}, id interface{}, in interface{}) *MockRepository_UpdateStaff_Call {
	return &MockRepository_UpdateStaff_Call{Call: _e.mock.On("UpdateStaff", ctx, id, in)}
}

func (_c *MockRepository_UpdateStaff_Call) Run(run func(ctx context.Context, id uint, in UpdateStaffRequest)) *MockRepository_UpdateStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(UpdateStaffRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateStaff_Call) Return(_a0 *Staff, _a1 error) *MockRepository_UpdateStaff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateStaff_Call) RunAndReturn(run func(context.Context, uint, UpdateStaffRequest) (*Staff, error)) *MockRepository_UpdateStaff_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyManagerPIN provides a mock function with given fields: ctx
func (_m *MockRepository) VerifyManagerPIN(ctx context.Context) (*Staff, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for VerifyManagerPIN")
	}

	var r0 *Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*Staff, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *Staff); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_VerifyManagerPIN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyManagerPIN'
type MockRepository_VerifyManagerPIN_Call struct {
	*mock.Call
}

// VerifyManagerPIN is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) VerifyManagerPIN(ctx interface{}) *MockRepository_VerifyManagerPIN_Call {
	return &MockRepository_VerifyManagerPIN_Call{Call: _e.mock.On("VerifyManagerPIN", ctx)}
}

func (_c *MockRepository_VerifyManagerPIN_Call) Run(run func(ctx context.Context)) *MockRepository_VerifyManagerPIN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_VerifyManagerPIN_Call) Return(_a0 *Staff, _a1 error) *MockRepository_VerifyManagerPIN_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_VerifyManagerPIN_Call) RunAndReturn(run func(context.Context) (*Staff, error)) *MockRepository_VerifyManagerPIN_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyStaffPIN provides a mock function with given fields: ctx, id
func (_m *MockRepository) VerifyStaffPIN(ctx context.Context, id uint) (*Staff, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for VerifyStaffPIN")
	}

	var r0 *Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*Staff, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *Staff); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_VerifyStaffPIN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyStaffPIN'
type MockRepository_VerifyStaffPIN_Call struct {
	*mock.Call
}

// VerifyStaffPIN is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRepository_Expecter) VerifyStaffPIN(ctx interface{}, id interface{}) *MockRepository_VerifyStaffPIN_Call {
	return &MockRepository_VerifyStaffPIN_Call{Call: _e.mock.On("VerifyStaffPIN", ctx, id)}
}

func (_c *MockRepository_VerifyStaffPIN_Call) Run(run func(ctx context.Context, id uint)) *MockRepository_VerifyStaffPIN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_VerifyStaffPIN_Call) Return(_a0 *Staff, _a1 error) *MockRepository_VerifyStaffPIN_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_VerifyStaffPIN_Call) RunAndReturn(run func(context.Context, uint) (*Staff, error)) *MockRepository_VerifyStaffPIN_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
