// Code generated by mockery v2.53.3. DO NOT EDIT.

package identity

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateBranch provides a mock function with given fields: ctx, orgID, in
func (_m *MockRepository) CreateBranch(ctx context.Context, orgID uint, in CreateBranchRequest) (*Branch, error) {
	ret := _m.Called(ctx, orgID, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateBranch")
	}

	var r0 *Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, CreateBranchRequest) (*Branch, error)); ok {
		return rf(ctx, orgID, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, CreateBranchRequest) *Branch); ok {
		r0 = rf(ctx, orgID, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, CreateBranchRequest) error); ok {
		r1 = rf(ctx, orgID, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBranch'
type MockRepository_CreateBranch_Call struct {
	*mock.Call
}

// CreateBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - in CreateBranchRequest
func (_e *MockRepository_Expecter) CreateBranch(ctx interface{}, orgID interface{}, in interface{}) *MockRepository_CreateBranch_Call {
	return &MockRepository_CreateBranch_Call{Call: _e.mock.On("CreateBranch", ctx, orgID, in)}
}

func (_c *MockRepository_CreateBranch_Call) Run(run func(ctx context.Context, orgID uint, in CreateBranchRequest)) *MockRepository_CreateBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(CreateBranchRequest))
	})
	return _c
}

func (_c *MockRepository_CreateBranch_Call) Return(_a0 *Branch, _a1 error) *MockRepository_CreateBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateBranch_Call) RunAndReturn(run func(context.Context, uint, CreateBranchRequest) (*Branch, error)) *MockRepository_CreateBranch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDevice provides a mock function with given fields: ctx, orgID, in
func (_m *MockRepository) CreateDevice(ctx context.Context, orgID uint, in CreateDeviceRequest) (*Device, error) {
	ret := _m.Called(ctx, orgID, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateDevice")
	}

	var r0 *Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, CreateDeviceRequest) (*Device, error)); ok {
		return rf(ctx, orgID, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, CreateDeviceRequest) *Device); ok {
		r0 = rf(ctx, orgID, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, CreateDeviceRequest) error); ok {
		r1 = rf(ctx, orgID, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDevice'
type MockRepository_CreateDevice_Call struct {
	*mock.Call
}

// CreateDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - in CreateDeviceRequest
func (_e *MockRepository_Expecter) CreateDevice(ctx interface{}, orgID interface{}, in interface{}) *MockRepository_CreateDevice_Call {
	return &MockRepository_CreateDevice_Call{Call: _e.mock.On("CreateDevice", ctx, orgID, in)}
}

func (_c *MockRepository_CreateDevice_Call) Run(run func(ctx context.Context, orgID uint, in CreateDeviceRequest)) *MockRepository_CreateDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(CreateDeviceRequest))
	})
	return _c
}

func (_c *MockRepository_CreateDevice_Call) Return(_a0 *Device, _a1 error) *MockRepository_CreateDevice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateDevice_Call) RunAndReturn(run func(context.Context, uint, CreateDeviceRequest) (*Device, error)) *MockRepository_CreateDevice_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrganization provides a mock function with given fields: db, org
func (_m *MockRepository) CreateOrganization(db *gorm.DB, org *Organization) error {
	ret := _m.Called(db, org)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *Organization) error); ok {
		r0 = rf(db, org)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganization'
type MockRepository_CreateOrganization_Call struct {
	*mock.Call
}

// CreateOrganization is a helper method to define mock.On call
//   - db *gorm.DB
//   - org *Organization
func (_e *MockRepository_Expecter) CreateOrganization(db interface{}, org interface{}) *MockRepository_CreateOrganization_Call {
	return &MockRepository_CreateOrganization_Call{Call: _e.mock.On("CreateOrganization", db, org)}
}

func (_c *MockRepository_CreateOrganization_Call) Run(run func(db *gorm.DB, org *Organization)) *MockRepository_CreateOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*Organization))
	})
	return _c
}

func (_c *MockRepository_CreateOrganization_Call) Return(_a0 error) *MockRepository_CreateOrganization_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateOrganization_Call) RunAndReturn(run func(*gorm.DB, *Organization) error) *MockRepository_CreateOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePosAccount provides a mock function with given fields: ctx, in
func (_m *MockRepository) CreatePosAccount(ctx context.Context, in CreatePosAccountInput) (*User, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreatePosAccount")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, CreatePosAccountInput) (*User, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, CreatePosAccountInput) *User); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, CreatePosAccountInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreatePosAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePosAccount'
type MockRepository_CreatePosAccount_Call struct {
	*mock.Call
}

// CreatePosAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - in CreatePosAccountInput
func (_e *MockRepository_Expecter) CreatePosAccount(ctx interface{}, in interface{}) *MockRepository_CreatePosAccount_Call {
	return &MockRepository_CreatePosAccount_Call{Call: _e.mock.On("CreatePosAccount", ctx, in)}
}

func (_c *MockRepository_CreatePosAccount_Call) Run(run func(ctx context.Context, in CreatePosAccountInput)) *MockRepository_CreatePosAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(CreatePosAccountInput))
	})
	return _c
}

func (_c *MockRepository_CreatePosAccount_Call) Return(_a0 *User, _a1 error) *MockRepository_CreatePosAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreatePosAccount_Call) RunAndReturn(run func(context.Context, CreatePosAccountInput) (*User, error)) *MockRepository_CreatePosAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function with given fields: ctx, userID, refreshHash, expiresAt
func (_m *MockRepository) CreateSession(ctx context.Context, userID uint, refreshHash string, expiresAt time.Time) (*Session, error) {
	ret := _m.Called(ctx, userID, refreshHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, time.Time) (*Session, error)); ok {
		return rf(ctx, userID, refreshHash, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, time.Time) *Session); ok {
		r0 = rf(ctx, userID, refreshHash, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string, time.Time) error); ok {
		r1 = rf(ctx, userID, refreshHash, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - refreshHash string
//   - expiresAt time.Time
func (_e *MockRepository_Expecter) CreateSession(ctx interface{}, userID interface{}, refreshHash interface{}, expiresAt interface{}) *MockRepository_CreateSession_Call {
	return &MockRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID, refreshHash, expiresAt)}
}

func (_c *MockRepository_CreateSession_Call) Run(run func(ctx context.Context, userID uint, refreshHash string, expiresAt time.Time)) *MockRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepository_CreateSession_Call) Return(_a0 *Session, _a1 error) *MockRepository_CreateSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateSession_Call) RunAndReturn(run func(context.Context, uint, string, time.Time) (*Session, error)) *MockRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStaff provides a mock function with given fields: ctx, orgID, in
func (_m *MockRepository) CreateStaff(ctx context.Context, orgID uint, in CreateStaffRequest) (*Staff, error) {
	ret := _m.Called(ctx, orgID, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateStaff")
	}

	var r0 *Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, CreateStaffRequest) (*Staff, error)); ok {
		return rf(ctx, orgID, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, CreateStaffRequest) *Staff); ok {
		r0 = rf(ctx, orgID, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, CreateStaffRequest) error); ok {
		r1 = rf(ctx, orgID, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStaff'
type MockRepository_CreateStaff_Call struct {
	*mock.Call
}

// CreateStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - in CreateStaffRequest
func (_e *MockRepository_Expecter) CreateStaff(ctx interface{}, orgID interface{}, in interface{}) *MockRepository_CreateStaff_Call {
	return &MockRepository_CreateStaff_Call{Call: _e.mock.On("CreateStaff", ctx, orgID, in)}
}

func (_c *MockRepository_CreateStaff_Call) Run(run func(ctx context.Context, orgID uint, in CreateStaffRequest)) *MockRepository_CreateStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(CreateStaffRequest))
	})
	return _c
}

func (_c *MockRepository_CreateStaff_Call) Return(_a0 *Staff, _a1 error) *MockRepository_CreateStaff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateStaff_Call) RunAndReturn(run func(context.Context, uint, CreateStaffRequest) (*Staff, error)) *MockRepository_CreateStaff_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: db, user
func (_m *MockRepository) CreateUser(db *gorm.DB, user *User) error {
	ret := _m.Called(db, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *User) error); ok {
		r0 = rf(db, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - db *gorm.DB
//   - user *User
func (_e *MockRepository_Expecter) CreateUser(db interface{}, user interface{}) *MockRepository_CreateUser_Call {
	return &MockRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", db, user)}
}

func (_c *MockRepository_CreateUser_Call) Run(run func(db *gorm.DB, user *User)) *MockRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*User))
	})
	return _c
}

func (_c *MockRepository_CreateUser_Call) Return(_a0 error) *MockRepository_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateUser_Call) RunAndReturn(run func(*gorm.DB, *User) error) *MockRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetBranch provides a mock function with given fields: ctx, orgID, id
func (_m *MockRepository) GetBranch(ctx context.Context, orgID uint, id uint) (*Branch, error) {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBranch")
	}

	var r0 *Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*Branch, error)); ok {
		return rf(ctx, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *Branch); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBranch'
type MockRepository_GetBranch_Call struct {
	*mock.Call
}

// GetBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - id uint
func (_e *MockRepository_Expecter) GetBranch(ctx interface{}, orgID interface{}, id interface{}) *MockRepository_GetBranch_Call {
	return &MockRepository_GetBranch_Call{Call: _e.mock.On("GetBranch", ctx, orgID, id)}
}

func (_c *MockRepository_GetBranch_Call) Run(run func(ctx context.Context, orgID uint, id uint)) *MockRepository_GetBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockRepository_GetBranch_Call) Return(_a0 *Branch, _a1 error) *MockRepository_GetBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetBranch_Call) RunAndReturn(run func(context.Context, uint, uint) (*Branch, error)) *MockRepository_GetBranch_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByRefreshHash provides a mock function with given fields: ctx, refreshHash
func (_m *MockRepository) GetSessionByRefreshHash(ctx context.Context, refreshHash string) (*Session, error) {
	ret := _m.Called(ctx, refreshHash)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByRefreshHash")
	}

	var r0 *Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Session, error)); ok {
		return rf(ctx, refreshHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Session); ok {
		r0 = rf(ctx, refreshHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetSessionByRefreshHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByRefreshHash'
type MockRepository_GetSessionByRefreshHash_Call struct {
	*mock.Call
}

// GetSessionByRefreshHash is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshHash string
func (_e *MockRepository_Expecter) GetSessionByRefreshHash(ctx interface{}, refreshHash interface{}) *MockRepository_GetSessionByRefreshHash_Call {
	return &MockRepository_GetSessionByRefreshHash_Call{Call: _e.mock.On("GetSessionByRefreshHash", ctx, refreshHash)}
}

func (_c *MockRepository_GetSessionByRefreshHash_Call) Run(run func(ctx context.Context, refreshHash string)) *MockRepository_GetSessionByRefreshHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetSessionByRefreshHash_Call) Return(_a0 *Session, _a1 error) *MockRepository_GetSessionByRefreshHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetSessionByRefreshHash_Call) RunAndReturn(run func(context.Context, string) (*Session, error)) *MockRepository_GetSessionByRefreshHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetStaff provides a mock function with given fields: ctx, orgID, id
func (_m *MockRepository) GetStaff(ctx context.Context, orgID uint, id uint) (*Staff, error) {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetStaff")
	}

	var r0 *Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*Staff, error)); ok {
		return rf(ctx, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *Staff); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStaff'
type MockRepository_GetStaff_Call struct {
	*mock.Call
}

// GetStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - id uint
func (_e *MockRepository_Expecter) GetStaff(ctx interface{}, orgID interface{}, id interface{}) *MockRepository_GetStaff_Call {
	return &MockRepository_GetStaff_Call{Call: _e.mock.On("GetStaff", ctx, orgID, id)}
}

func (_c *MockRepository_GetStaff_Call) Run(run func(ctx context.Context, orgID uint, id uint)) *MockRepository_GetStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockRepository_GetStaff_Call) Return(_a0 *Staff, _a1 error) *MockRepository_GetStaff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetStaff_Call) RunAndReturn(run func(context.Context, uint, uint) (*Staff, error)) *MockRepository_GetStaff_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockRepository) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRepository_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockRepository_GetUserByEmail_Call {
	return &MockRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockRepository_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetUserByEmail_Call) Return(_a0 *User, _a1 error) *MockRepository_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*User, error)) *MockRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetUserByID(ctx context.Context, id uint) (*User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRepository_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockRepository_GetUserByID_Call {
	return &MockRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockRepository_GetUserByID_Call) Run(run func(ctx context.Context, id uint)) *MockRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_GetUserByID_Call) Return(_a0 *User, _a1 error) *MockRepository_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserByID_Call) RunAndReturn(run func(context.Context, uint) (*User, error)) *MockRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListBranchStaff provides a mock function with given fields: ctx, orgID, id
func (_m *MockRepository) ListBranchStaff(ctx context.Context, orgID uint, id uint) ([]Staff, error) {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for ListBranchStaff")
	}

	var r0 []Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) ([]Staff, error)); ok {
		return rf(ctx, orgID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) []Staff); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, orgID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListBranchStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBranchStaff'
type MockRepository_ListBranchStaff_Call struct {
	*mock.Call
}

// ListBranchStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - id uint
func (_e *MockRepository_Expecter) ListBranchStaff(ctx interface{}, orgID interface{}, id interface{}) *MockRepository_ListBranchStaff_Call {
	return &MockRepository_ListBranchStaff_Call{Call: _e.mock.On("ListBranchStaff", ctx, orgID, id)}
}

func (_c *MockRepository_ListBranchStaff_Call) Run(run func(ctx context.Context, orgID uint, id uint)) *MockRepository_ListBranchStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockRepository_ListBranchStaff_Call) Return(_a0 []Staff, _a1 error) *MockRepository_ListBranchStaff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListBranchStaff_Call) RunAndReturn(run func(context.Context, uint, uint) ([]Staff, error)) *MockRepository_ListBranchStaff_Call {
	_c.Call.Return(run)
	return _c
}

// ListBranches provides a mock function with given fields: ctx, orgID
func (_m *MockRepository) ListBranches(ctx context.Context, orgID uint) ([]Branch, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListBranches")
	}

	var r0 []Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]Branch, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []Branch); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListBranches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBranches'
type MockRepository_ListBranches_Call struct {
	*mock.Call
}

// ListBranches is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
func (_e *MockRepository_Expecter) ListBranches(ctx interface{}, orgID interface{}) *MockRepository_ListBranches_Call {
	return &MockRepository_ListBranches_Call{Call: _e.mock.On("ListBranches", ctx, orgID)}
}

func (_c *MockRepository_ListBranches_Call) Run(run func(ctx context.Context, orgID uint)) *MockRepository_ListBranches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_ListBranches_Call) Return(_a0 []Branch, _a1 error) *MockRepository_ListBranches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListBranches_Call) RunAndReturn(run func(context.Context, uint) ([]Branch, error)) *MockRepository_ListBranches_Call {
	_c.Call.Return(run)
	return _c
}

// ListDevices provides a mock function with given fields: ctx, orgID
func (_m *MockRepository) ListDevices(ctx context.Context, orgID uint) ([]Device, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListDevices")
	}

	var r0 []Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]Device, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []Device); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDevices'
type MockRepository_ListDevices_Call struct {
	*mock.Call
}

// ListDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
func (_e *MockRepository_Expecter) ListDevices(ctx interface{}, orgID interface{}) *MockRepository_ListDevices_Call {
	return &MockRepository_ListDevices_Call{Call: _e.mock.On("ListDevices", ctx, orgID)}
}

func (_c *MockRepository_ListDevices_Call) Run(run func(ctx context.Context, orgID uint)) *MockRepository_ListDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_ListDevices_Call) Return(_a0 []Device, _a1 error) *MockRepository_ListDevices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListDevices_Call) RunAndReturn(run func(context.Context, uint) ([]Device, error)) *MockRepository_ListDevices_Call {
	_c.Call.Return(run)
	return _c
}

// ListPermissions provides a mock function with given fields: ctx
func (_m *MockRepository) ListPermissions(ctx context.Context) ([]Permission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPermissions")
	}

	var r0 []Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]Permission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPermissions'
type MockRepository_ListPermissions_Call struct {
	*mock.Call
}

// ListPermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListPermissions(ctx interface{}) *MockRepository_ListPermissions_Call {
	return &MockRepository_ListPermissions_Call{Call: _e.mock.On("ListPermissions", ctx)}
}

func (_c *MockRepository_ListPermissions_Call) Run(run func(ctx context.Context)) *MockRepository_ListPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListPermissions_Call) Return(_a0 []Permission, _a1 error) *MockRepository_ListPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListPermissions_Call) RunAndReturn(run func(context.Context) ([]Permission, error)) *MockRepository_ListPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// ListRolePermissions provides a mock function with given fields: ctx, id
func (_m *MockRepository) ListRolePermissions(ctx context.Context, id uint) ([]Permission, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ListRolePermissions")
	}

	var r0 []Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]Permission, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []Permission); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListRolePermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRolePermissions'
type MockRepository_ListRolePermissions_Call struct {
	*mock.Call
}

// ListRolePermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRepository_Expecter) ListRolePermissions(ctx interface{}, id interface{}) *MockRepository_ListRolePermissions_Call {
	return &MockRepository_ListRolePermissions_Call{Call: _e.mock.On("ListRolePermissions", ctx, id)}
}

func (_c *MockRepository_ListRolePermissions_Call) Run(run func(ctx context.Context, id uint)) *MockRepository_ListRolePermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_ListRolePermissions_Call) Return(_a0 []Permission, _a1 error) *MockRepository_ListRolePermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListRolePermissions_Call) RunAndReturn(run func(context.Context, uint) ([]Permission, error)) *MockRepository_ListRolePermissions_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoles provides a mock function with given fields: ctx
func (_m *MockRepository) ListRoles(ctx context.Context) ([]Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRoles")
	}

	var r0 []Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoles'
type MockRepository_ListRoles_Call struct {
	*mock.Call
}

// ListRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListRoles(ctx interface{}) *MockRepository_ListRoles_Call {
	return &MockRepository_ListRoles_Call{Call: _e.mock.On("ListRoles", ctx)}
}

func (_c *MockRepository_ListRoles_Call) Run(run func(ctx context.Context)) *MockRepository_ListRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListRoles_Call) Return(_a0 []Role, _a1 error) *MockRepository_ListRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListRoles_Call) RunAndReturn(run func(context.Context) ([]Role, error)) *MockRepository_ListRoles_Call {
	_c.Call.Return(run)
	return _c
}

// ListStaff provides a mock function with given fields: ctx, orgID
func (_m *MockRepository) ListStaff(ctx context.Context, orgID uint) ([]Staff, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListStaff")
	}

	var r0 []Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]Staff, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []Staff); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStaff'
type MockRepository_ListStaff_Call struct {
	*mock.Call
}

// ListStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
func (_e *MockRepository_Expecter) ListStaff(ctx interface{}, orgID interface{}) *MockRepository_ListStaff_Call {
	return &MockRepository_ListStaff_Call{Call: _e.mock.On("ListStaff", ctx, orgID)}
}

func (_c *MockRepository_ListStaff_Call) Run(run func(ctx context.Context, orgID uint)) *MockRepository_ListStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_ListStaff_Call) Return(_a0 []Staff, _a1 error) *MockRepository_ListStaff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListStaff_Call) RunAndReturn(run func(context.Context, uint) ([]Staff, error)) *MockRepository_ListStaff_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function with given fields: ctx, sessionID
func (_m *MockRepository) RevokeSession(ctx context.Context, sessionID uint) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockRepository_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uint
func (_e *MockRepository_Expecter) RevokeSession(ctx interface{}, sessionID interface{}) *MockRepository_RevokeSession_Call {
	return &MockRepository_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, sessionID)}
}

func (_c *MockRepository_RevokeSession_Call) Run(run func(ctx context.Context, sessionID uint)) *MockRepository_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRepository_RevokeSession_Call) Return(_a0 error) *MockRepository_RevokeSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_RevokeSession_Call) RunAndReturn(run func(context.Context, uint) error) *MockRepository_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBranch provides a mock function with given fields: ctx, orgID, id, in
func (_m *MockRepository) UpdateBranch(ctx context.Context, orgID uint, id uint, in UpdateBranchRequest) (*Branch, error) {
	ret := _m.Called(ctx, orgID, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBranch")
	}

	var r0 *Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, UpdateBranchRequest) (*Branch, error)); ok {
		return rf(ctx, orgID, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, UpdateBranchRequest) *Branch); ok {
		r0 = rf(ctx, orgID, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, UpdateBranchRequest) error); ok {
		r1 = rf(ctx, orgID, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBranch'
type MockRepository_UpdateBranch_Call struct {
	*mock.Call
}

// UpdateBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - id uint
//   - in UpdateBranchRequest
func (_e *MockRepository_Expecter) UpdateBranch(ctx interface{}, orgID interface{}, id interface{}, in interface{}) *MockRepository_UpdateBranch_Call {
	return &MockRepository_UpdateBranch_Call{Call: _e.mock.On("UpdateBranch", ctx, orgID, id, in)}
}

func (_c *MockRepository_UpdateBranch_Call) Run(run func(ctx context.Context, orgID uint, id uint, in UpdateBranchRequest)) *MockRepository_UpdateBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(UpdateBranchRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateBranch_Call) Return(_a0 *Branch, _a1 error) *MockRepository_UpdateBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateBranch_Call) RunAndReturn(run func(context.Context, uint, uint, UpdateBranchRequest) (*Branch, error)) *MockRepository_UpdateBranch_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDevice provides a mock function with given fields: ctx, orgID, id, in
func (_m *MockRepository) UpdateDevice(ctx context.Context, orgID uint, id uint, in UpdateDeviceRequest) (*Device, error) {
	ret := _m.Called(ctx, orgID, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDevice")
	}

	var r0 *Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, UpdateDeviceRequest) (*Device, error)); ok {
		return rf(ctx, orgID, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, UpdateDeviceRequest) *Device); ok {
		r0 = rf(ctx, orgID, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, UpdateDeviceRequest) error); ok {
		r1 = rf(ctx, orgID, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDevice'
type MockRepository_UpdateDevice_Call struct {
	*mock.Call
}

// UpdateDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - id uint
//   - in UpdateDeviceRequest
func (_e *MockRepository_Expecter) UpdateDevice(ctx interface{}, orgID interface{}, id interface{}, in interface{}) *MockRepository_UpdateDevice_Call {
	return &MockRepository_UpdateDevice_Call{Call: _e.mock.On("UpdateDevice", ctx, orgID, id, in)}
}

func (_c *MockRepository_UpdateDevice_Call) Run(run func(ctx context.Context, orgID uint, id uint, in UpdateDeviceRequest)) *MockRepository_UpdateDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(UpdateDeviceRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateDevice_Call) Return(_a0 *Device, _a1 error) *MockRepository_UpdateDevice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateDevice_Call) RunAndReturn(run func(context.Context, uint, uint, UpdateDeviceRequest) (*Device, error)) *MockRepository_UpdateDevice_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMe provides a mock function with given fields: ctx, userID, in
func (_m *MockRepository) UpdateMe(ctx context.Context, userID uint, in UpdateMeRequest) (*User, error) {
	ret := _m.Called(ctx, userID, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMe")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, UpdateMeRequest) (*User, error)); ok {
		return rf(ctx, userID, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, UpdateMeRequest) *User); ok {
		r0 = rf(ctx, userID, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, UpdateMeRequest) error); ok {
		r1 = rf(ctx, userID, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMe'
type MockRepository_UpdateMe_Call struct {
	*mock.Call
}

// UpdateMe is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - in UpdateMeRequest
func (_e *MockRepository_Expecter) UpdateMe(ctx interface{}, userID interface{}, in interface{}) *MockRepository_UpdateMe_Call {
	return &MockRepository_UpdateMe_Call{Call: _e.mock.On("UpdateMe", ctx, userID, in)}
}

func (_c *MockRepository_UpdateMe_Call) Run(run func(ctx context.Context, userID uint, in UpdateMeRequest)) *MockRepository_UpdateMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(UpdateMeRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateMe_Call) Return(_a0 *User, _a1 error) *MockRepository_UpdateMe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateMe_Call) RunAndReturn(run func(context.Context, uint, UpdateMeRequest) (*User, error)) *MockRepository_UpdateMe_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStaff provides a mock function with given fields: ctx, orgID, id, in
func (_m *MockRepository) UpdateStaff(ctx context.Context, orgID uint, id uint, in UpdateStaffRequest) (*Staff, error) {
	ret := _m.Called(ctx, orgID, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStaff")
	}

	var r0 *Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, UpdateStaffRequest) (*Staff, error)); ok {
		return rf(ctx, orgID, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, UpdateStaffRequest) *Staff); ok {
		r0 = rf(ctx, orgID, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, UpdateStaffRequest) error); ok {
		r1 = rf(ctx, orgID, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStaff'
type MockRepository_UpdateStaff_Call struct {
	*mock.Call
}

// UpdateStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uint
//   - id uint
//   - in UpdateStaffRequest
func (_e *MockRepository_Expecter) UpdateStaff(ctx interface{}, orgID interface{}, id interface{}, in interface{}) *MockRepository_UpdateStaff_Call {
	return &MockRepository_UpdateStaff_Call{Call: _e.mock.On("UpdateStaff", ctx, orgID, id, in)}
}

func (_c *MockRepository_UpdateStaff_Call) Run(run func(ctx context.Context, orgID uint, id uint, in UpdateStaffRequest)) *MockRepository_UpdateStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(UpdateStaffRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateStaff_Call) Return(_a0 *Staff, _a1 error) *MockRepository_UpdateStaff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateStaff_Call) RunAndReturn(run func(context.Context, uint, uint, UpdateStaffRequest) (*Staff, error)) *MockRepository_UpdateStaff_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyManagerPIN provides a mock function with given fields: ctx
func (_m *MockRepository) VerifyManagerPIN(ctx context.Context) (*Staff, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for VerifyManagerPIN")
	}

	var r0 *Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*Staff, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *Staff); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_VerifyManagerPIN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyManagerPIN'
type MockRepository_VerifyManagerPIN_Call struct {
	*mock.Call
}

// VerifyManagerPIN is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) VerifyManagerPIN(ctx interface{}) *MockRepository_VerifyManagerPIN_Call {
	return &MockRepository_VerifyManagerPIN_Call{Call: _e.mock.On("VerifyManagerPIN", ctx)}
}

func (_c *MockRepository_VerifyManagerPIN_Call) Run(run func(ctx context.Context)) *MockRepository_VerifyManagerPIN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_VerifyManagerPIN_Call) Return(_a0 *Staff, _a1 error) *MockRepository_VerifyManagerPIN_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_VerifyManagerPIN_Call) RunAndReturn(run func(context.Context) (*Staff, error)) *MockRepository_VerifyManagerPIN_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
