package shift

import (
	"context"
	"time"
)

// Repository defines the shift domain's persistence operations.
type Repository interface {
	OpenShift(ctx context.Context, in OpenShiftRequest) (*Shift, error)
	// GetCurrentShift resolves the POS account's paired device from userID;
	// orgID prevents a caller from probing a user in another tenant.
	GetCurrentShift(ctx context.Context, orgID, userID uint) (*Shift, error)
	// GetShift returns NotFound for both a missing ID and an ID whose branch
	// belongs to another organization, preventing tenant enumeration.
	GetShift(ctx context.Context, orgID, id uint) (*Shift, error)
	// CloseShift atomically transitions an open shift and writes its payment
	// reconciliation snapshot. closedAt is generated by the service.
	CloseShift(ctx context.Context, orgID, id uint, closedAt time.Time) (*Shift, error)
	GetShiftSummary(ctx context.Context, id uint) (map[string]any, error)
	ListShiftReconciliations(ctx context.Context, id uint) ([]ShiftReconciliation, error)
	CreateDrawerEvent(ctx context.Context, in CreateDrawerEventRequest) (*DrawerEvent, error)
	ListDrawerEvents(ctx context.Context) ([]DrawerEvent, error)
	ListExpenses(ctx context.Context) ([]Expense, error)
	CreateExpense(ctx context.Context, in CreateExpenseRequest) (*Expense, error)
	UpdateExpense(ctx context.Context, id uint, in UpdateExpenseRequest) (*Expense, error)
	DeleteExpense(ctx context.Context, id uint) error
}
