package shift

import (
	"context"
	"time"
)

// Repository defines the shift domain's persistence operations.
type Repository interface {
	OpenShift(ctx context.Context, in OpenShiftRequest) (*Shift, error)
	// GetCurrentShift resolves the POS account's paired device from userID;
	// orgID prevents a caller from probing a user in another tenant.
	GetCurrentShift(ctx context.Context, orgID, userID uint) (*Shift, error)
	// GetShift returns NotFound for both a missing ID and an ID whose branch
	// belongs to another organization, preventing tenant enumeration.
	GetShift(ctx context.Context, scope AccessScope, id uint) (*Shift, error)
	// CloseShift atomically transitions an open shift and writes its payment
	// reconciliation snapshot. closedAt is generated by the service. in
	// carries the physically-counted cash amount - see CloseShiftRequest.
	// staffID must match the shift's own StaffID (whoever opened it) - a
	// shift can only be closed by the same staff member who opened it, no
	// exceptions - returns common.ForbiddenError otherwise.
	CloseShift(ctx context.Context, scope AccessScope, id uint, closedAt time.Time, staffID uint, in CloseShiftRequest) (*Shift, error)
	GetShiftSummary(ctx context.Context, scope AccessScope, id uint) (map[string]any, error)
	ListShiftReconciliations(ctx context.Context, scope AccessScope, id uint) ([]ShiftReconciliation, error)
	CreateDrawerEvent(ctx context.Context, scope AccessScope, in CreateDrawerEventRequest) (*DrawerEvent, error)
	ListDrawerEvents(ctx context.Context, scope AccessScope) ([]DrawerEvent, error)
	ListExpenses(ctx context.Context, scope AccessScope) ([]Expense, error)
	CreateExpense(ctx context.Context, scope AccessScope, in CreateExpenseRequest) (*Expense, error)
	// UpdateExpense and DeleteExpense return common.ForbiddenError if actor
	// isn't the expense's own CreatedBy and doesn't have CanManageAny (a
	// Manager, via access_backoffice) - see ExpenseActor.
	UpdateExpense(ctx context.Context, scope AccessScope, id uint, actor ExpenseActor, in UpdateExpenseRequest) (*Expense, error)
	DeleteExpense(ctx context.Context, scope AccessScope, id uint, actor ExpenseActor) error
}
